# Generated by Django 5.2.5 on 2025-09-22 16:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la sucursal', max_length=100)),
                ('direccion', models.TextField(blank=True, help_text='Dirección de la sucursal')),
                ('responsable', models.CharField(blank=True, help_text='Persona responsable', max_length=100)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de contacto', max_length=20)),
                ('activa', models.BooleanField(default=True, help_text='Sucursal activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Sucursales',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('limpieza', 'Limpieza'), ('seguridad', 'Seguridad'), ('oficina', 'Oficina'), ('etiquetas', 'Etiquetas'), ('envases', 'Envases y Contenedores'), ('herramientas', 'Herramientas'), ('otros', 'Otros')], default='otros', help_text='Categoría del producto', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo_qr',
            field=models.CharField(default='', editable=False, help_text='Código QR único del producto', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Costo por unidad', max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, help_text='Última actualización'),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.CharField(blank=True, help_text='Proveedor del producto', max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=5, help_text='Cantidad mínima antes de alerta'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('consumible', 'Consumible'), ('reutilizable', 'Reutilizable')], default='consumible', help_text='Tipo de producto', max_length=15),
        ),
        migrations.AddField(
            model_name='producto',
            name='ubicacion',
            field=models.CharField(blank=True, help_text='Ubicación física en almacén', max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad actual en stock'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción detallada del producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado_calidad',
            field=models.CharField(choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], default='bueno', help_text='Estado de calidad del producto', max_length=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_ingreso',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de registro en el sistema'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(help_text='Nombre del producto', max_length=100),
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste de Inventario'), ('devolucion', 'Devolución')], help_text='Tipo de movimiento', max_length=15)),
                ('cantidad', models.PositiveIntegerField(help_text='Cantidad del movimiento')),
                ('motivo', models.CharField(choices=[('compra', 'Compra'), ('entrega_empleado', 'Entrega a Empleado'), ('envio_sucursal', 'Envío a Sucursal'), ('uso_interno', 'Uso Interno'), ('ajuste_inventario', 'Ajuste de Inventario'), ('producto_dañado', 'Producto Dañado'), ('devolucion', 'Devolución'), ('otro', 'Otro')], help_text='Motivo del movimiento', max_length=20)),
                ('destinatario', models.CharField(blank=True, help_text='Nombre del destinatario', max_length=100)),
                ('area_destino', models.CharField(blank=True, help_text='Área o departamento destino', max_length=100)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones del movimiento')),
                ('numero_proyecto', models.CharField(blank=True, help_text='Número de proyecto (opcional)', max_length=50)),
                ('fecha_movimiento', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora del movimiento')),
                ('usuario_registro', models.CharField(help_text='Usuario que registra el movimiento', max_length=50)),
                ('stock_anterior', models.PositiveIntegerField(help_text='Stock antes del movimiento')),
                ('stock_posterior', models.PositiveIntegerField(help_text='Stock después del movimiento')),
                ('producto', models.ForeignKey(help_text='Producto involucrado', on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
                ('sucursal_destino', models.ForeignKey(blank=True, help_text='Sucursal destino', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.sucursal')),
            ],
            options={
                'verbose_name_plural': 'Movimientos',
                'ordering': ['-fecha_movimiento'],
            },
        ),
    ]
