# Generated by Django 5.2.5 on 2025-09-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_sucursal_producto_categoria_producto_codigo_qr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='ciudad',
            field=models.CharField(blank=True, help_text='Ciudad donde se ubica', max_length=100),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código único de la sucursal', max_length=20),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='email',
            field=models.EmailField(blank=True, help_text='Correo electrónico de contacto', max_length=254),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='estado_provincia',
            field=models.CharField(blank=True, help_text='Estado o provincia', max_length=100),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones adicionales'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='responsable',
            field=models.CharField(blank=True, help_text='Persona responsable/encargado', max_length=100),
        ),
    ]
