# Generated by Django 5.2.5 on 2025-09-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_sucursal_ciudad_sucursal_codigo_sucursal_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='codigo',
            field=models.CharField(help_text='Código único de la sucursal', max_length=20, unique=True),
        ),
    ]
