# Generated by Django 5.2.5 on 2025-09-22 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_sucursal_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(help_text='Nombre completo del empleado', max_length=100)),
                ('cargo', models.CharField(help_text='Cargo o puesto del empleado', max_length=50)),
                ('area', models.CharField(help_text='Área donde trabaja (ej: Laboratorio, Oficina)', max_length=50)),
                ('activo', models.BooleanField(default=True, help_text='Empleado activo en la empresa')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, help_text='Fecha de registro en el sistema')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Última actualización del registro')),
            ],
            options={
                'verbose_name_plural': 'Empleados',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.AddField(
            model_name='movimiento',
            name='empleado_destinatario',
            field=models.ForeignKey(blank=True, help_text='Empleado destinatario del movimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_recibidos', to='inventario.empleado'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='usuario_registro_empleado',
            field=models.ForeignKey(blank=True, help_text='Empleado que registra el movimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_registrados', to='inventario.empleado'),
        ),
    ]
