# Generated by Django 5.2.5 on 2025-09-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_empleado_movimiento_empleado_destinatario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='cantidad_fraccionaria',
            field=models.FloatField(blank=True, help_text='Cantidad exacta en unidad base (ej: 600ml)', null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='es_movimiento_fraccionario',
            field=models.BooleanField(default=False, help_text='Indica si este movimiento es fraccionario (consumo parcial)'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='unidad_utilizada',
            field=models.CharField(blank=True, help_text='Unidad de medida utilizada (ml, gramos, etc.)', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidad_actual',
            field=models.FloatField(default=0.0, help_text='Cantidad real disponible en la unidad base'),
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidad_minima_alerta',
            field=models.FloatField(default=0.0, help_text='Alerta cuando esté por debajo de este nivel'),
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidad_unitaria',
            field=models.FloatField(default=1.0, help_text='Cantidad por unidad completa (ej: 1000ml por botella)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='es_fraccionable',
            field=models.BooleanField(default=False, help_text='¿Se puede consumir en porciones? (ej: líquidos, granulados)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_base',
            field=models.CharField(default='unidades', help_text='Unidad de medida (ml, litros, kg, gramos, etc.)', max_length=20),
        ),
    ]
