# Generated by Django 5.2.5 on 2025-09-25 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_agregar_campos_fraccionarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_objeto_unico',
            field=models.BooleanField(default=False, help_text='Marcar si es un producto único que se presta (permite stock mínimo 0, alerta solo cuando cantidad = 0)', verbose_name='Objeto Único'),
        ),
    ]
