# Generated by Django 5.2.5 on 2025-09-25 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_producto_es_objeto_unico'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='cantidad_fraccionaria_resultante',
            field=models.FloatField(blank=True, help_text='Cantidad fraccionaria restante en unidad base después del movimiento', null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='porcentaje_resultante',
            field=models.FloatField(blank=True, help_text='Porcentaje (0-100) restante de la unidad actual después del movimiento', null=True),
        ),
    ]
