# Generated by Django 5.2.5 on 2025-10-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_movimiento_cantidad_fraccionaria_resultante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='email',
            field=models.EmailField(blank=True, help_text='Correo electrónico del empleado (para notificaciones)', max_length=254, null=True),
        ),
    ]
