# Generated by Django 5.2.5 on 2025-10-01 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_empleado_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='sucursal',
            field=models.ForeignKey(blank=True, help_text='Sucursal a la que pertenece el empleado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='inventario.sucursal'),
        ),
    ]
