# Generated by Django 5.2.5 on 2025-10-01 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_empleado_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='jefe_directo',
            field=models.ForeignKey(blank=True, help_text='Jefe directo del empleado en la jerarquía organizacional', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to='inventario.empleado', verbose_name='Jefe Directo'),
        ),
    ]
