# Generated by Django 5.2.5 on 2025-10-04 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_empleado_jefe_directo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='contraseña_configurada',
            field=models.BooleanField(default=False, help_text='Indica si el empleado ya cambió su contraseña temporal', verbose_name='Contraseña configurada'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_activacion_acceso',
            field=models.DateTimeField(blank=True, help_text='Fecha en que el empleado completó su primer cambio de contraseña', null=True, verbose_name='Fecha de activación de acceso'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_envio_credenciales',
            field=models.DateTimeField(blank=True, help_text='Última vez que se enviaron las credenciales por email', null=True, verbose_name='Fecha de envío de credenciales'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tiene_acceso_sistema',
            field=models.BooleanField(default=False, help_text='Indica si el empleado puede iniciar sesión en el sistema', verbose_name='Tiene acceso al sistema'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Usuario de Django asociado para acceso al sistema', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleado', to=settings.AUTH_USER_MODEL, verbose_name='Usuario del Sistema'),
        ),
    ]
