# Generated by Django 5.2.5 on 2025-10-05 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_agregar_campos_acceso_sistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Foto del empleado para mostrar en el sistema (formatos: JPG, PNG, GIF)', null=True, upload_to='empleados/fotos/', verbose_name='Foto de Perfil'),
        ),
    ]
