# Generated by Django 5.2.5 on 2026-01-21 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_empleado_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='rol',
            field=models.CharField(choices=[('supervisor', 'Supervisor'), ('inspector', 'Inspector'), ('dispatcher', 'Dispatcher'), ('compras', 'Compras'), ('recepcionista', 'Recepcionista'), ('gerente_operacional', 'Gerente Operacional'), ('gerente_general', 'Gerente General'), ('tecnico', 'Técnico'), ('almacenista', 'Almacenista')], default='tecnico', help_text='Define los permisos y accesos del empleado en el sistema', max_length=30, verbose_name='Rol en el Sistema'),
        ),
    ]
