# Generated by Django 5.2.5 on 2026-02-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_empleado_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Foto del empleado para mostrar en el sistema (formatos: JPG, PNG, GIF)', max_length=255, null=True, upload_to='empleados/fotos/', verbose_name='Foto de Perfil'),
        ),
    ]
