# Generated by Django 5.2.5 on 2026-02-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_alter_empleado_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='numero_whatsapp',
            field=models.CharField(blank=True, help_text='Número local sin código de país, solo dígitos (ej: 5535458192). Opcional, solo si tiene línea empresarial.', max_length=15, null=True, verbose_name='WhatsApp empresarial'),
        ),
    ]
