# Generated by Django 5.2.5 on 2026-05-21 04:23

import config.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_agregar_numero_whatsapp_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Foto del empleado para mostrar en el sistema (JPG, PNG, GIF, WebP). Máx 10 MB.', max_length=255, null=True, upload_to='empleados/fotos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp']), config.validators.FileSizeValidator(10)], verbose_name='Foto de Perfil'),
        ),
    ]
