# Generated by Django 5.2.14 on 2026-08-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_sucursal_horario_atencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='mostrar_en_carga_trabajo',
            field=models.BooleanField(default=True, help_text='Si está activo, este técnico aparece en el panel de carga de órdenes activas (solo aplica con rol Técnico).', verbose_name='Mostrar en carga de trabajo'),
        ),
    ]
