# Generated by Django 5.2.14 on 2026-08-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0019_empleado_mostrar_en_carga_trabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='rol',
            field=models.CharField(
                choices=[
                    ('supervisor', 'Supervisor'),
                    ('inspector', 'Inspector'),
                    ('dispatcher', 'Dispatcher'),
                    ('compras', 'Compras'),
                    ('recepcionista', 'Recepcionista'),
                    ('gerente_operacional', 'Gerente Operacional'),
                    ('gerente_general', 'Gerente General'),
                    ('tecnico', 'Técnico'),
                    ('almacenista', 'Almacenista'),
                    ('facturacion', 'Facturación'),
                ],
                default='tecnico',
                help_text='Define los permisos y accesos del empleado en el sistema',
                max_length=30,
                verbose_name='Rol en el Sistema',
            ),
        ),
    ]
