# Generated by Django 5.2.14 on 2026-09-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0020_empleado_rol_facturacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='prefijo_facturacion',
            field=models.CharField(blank=True, help_text='Prefijo del webId del autofacturador (SAT, DROP, MTY, GDL). Vacío = no factura.', max_length=6, verbose_name='Prefijo de facturación'),
        ),
    ]
