# Generated by Django 5.2.5 on 2026-02-21 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Texto corto que aparece en la campanita', max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(help_text='Descripción extendida de lo que pasó', verbose_name='Mensaje detallado')),
                ('tipo', models.CharField(choices=[('exito', 'Éxito'), ('error', 'Error'), ('warning', 'Advertencia'), ('info', 'Información')], default='info', help_text='Determina el icono y color de la notificación', max_length=20, verbose_name='Tipo')),
                ('leida', models.BooleanField(default=False, help_text='Se marca True cuando el usuario abre el panel de notificaciones', verbose_name='Leída')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('task_id', models.CharField(blank=True, help_text='Identificador único de la tarea en Celery/Redis', max_length=255, null=True, verbose_name='ID de tarea Celery')),
                ('app_origen', models.CharField(blank=True, help_text='Módulo Django que generó la notificación (ej: servicio_tecnico)', max_length=100, null=True, verbose_name='App origen')),
                ('usuario', models.ForeignKey(blank=True, help_text='Quién debe ver esta notificación (vacío = global)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario destinatario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', '-fecha_creacion'], name='idx_notif_usuario_fecha'), models.Index(fields=['usuario', 'leida'], name='idx_notif_usuario_leida')],
            },
        ),
    ]
