# Generated by Django 5.2.5 on 2026-05-22 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(help_text='URL del servidor push del navegador (Google/Mozilla/Apple)', verbose_name='Endpoint')),
                ('p256dh', models.TextField(help_text='Clave pública de cifrado del navegador', verbose_name='Clave pública (p256dh)')),
                ('auth', models.TextField(help_text='Token secreto de autenticación del navegador', verbose_name='Auth secret')),
                ('activa', models.BooleanField(default=True, help_text='False si el usuario desactivó las notificaciones o la suscripción expiró', verbose_name='Activa')),
                ('fecha_creada', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de suscripción')),
                ('user_agent', models.CharField(blank=True, help_text='Navegador y dispositivo del usuario (informativo)', max_length=300, verbose_name='User Agent')),
                ('usuario', models.ForeignKey(help_text='Usuario dueño de esta suscripción', on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Suscripción Push',
                'verbose_name_plural': 'Suscripciones Push',
                'ordering': ['-fecha_creada'],
                'indexes': [models.Index(fields=['usuario', 'activa'], name='idx_push_usuario_activa')],
                'unique_together': {('usuario', 'endpoint')},
            },
        ),
    ]
