# Generated by Django 5.2.5 on 2026-05-30 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='url',
            field=models.CharField(blank=True, help_text='Si se especifica, al pulsar la notificación el usuario navega a esta URL', max_length=500, null=True, verbose_name='URL de destino'),
        ),
    ]
