# Generated by Django 5.2.5 on 2026-07-03 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0003_add_url_to_notificacion'),
        ('servicio_tecnico', '0042_piezacotizada_precio_unitario_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscriptionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(help_text='URL del servidor push del navegador (Google/Mozilla/Apple)', verbose_name='Endpoint')),
                ('p256dh', models.TextField(help_text='Clave pública de cifrado del navegador', verbose_name='Clave pública (p256dh)')),
                ('auth', models.TextField(help_text='Token secreto de autenticación del navegador', verbose_name='Auth secret')),
                ('activa', models.BooleanField(default=True, help_text='False si el cliente desactivó las notificaciones o la suscripción expiró', verbose_name='Activa')),
                ('fecha_creada', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de suscripción')),
                ('user_agent', models.CharField(blank=True, help_text='Navegador y dispositivo del cliente (informativo)', max_length=300, verbose_name='User Agent')),
                ('enlace', models.ForeignKey(help_text='Enlace (token) del cliente dueño de esta suscripción', on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='servicio_tecnico.enlaceseguimientocliente', verbose_name='Enlace de seguimiento')),
            ],
            options={
                'verbose_name': 'Suscripción Push de Cliente',
                'verbose_name_plural': 'Suscripciones Push de Clientes',
                'ordering': ['-fecha_creada'],
                'indexes': [models.Index(fields=['enlace', 'activa'], name='idx_push_cli_enlace_activa')],
                'unique_together': {('enlace', 'endpoint')},
            },
        ),
    ]
