# Generated by Django 5.2.5 on 2026-07-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0004_pushsubscriptioncliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsubscriptioncliente',
            name='fecha_desactivada',
            field=models.DateTimeField(blank=True, help_text='Momento en que el cliente desactivó push o la suscripción expiró', null=True, verbose_name='Fecha de desactivación'),
        ),
    ]
