# Generated by Django 5.2.5 on 2026-07-21 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0005_pushsubscriptioncliente_fecha_desactivada'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='categoria',
            field=models.CharField(db_index=True, default='general', help_text='Agrupación para pestañas de la campanita (ej. general, equipo_disponible)', max_length=40, verbose_name='Categoría'),
        ),
    ]
