# Generated by Django 5.2.14 on 2026-08-28

from django.db import migrations, models


def marcar_equipo_listo_como_accion(apps, schema_editor):
    """
    Pasa a «Por hacer» los avisos vivos de equipo listo para avisar al cliente.

    EXPLICACIÓN: El resto histórico caduca a los 7 días; no clasificamos
    cotizaciones/pagos viejos. Las confirmaciones «Equipo disponible notificado»
    no empiezan con «Equipo listo» y se quedan en Avisos.
    """
    Notificacion = apps.get_model('notificaciones', 'Notificacion')
    Notificacion.objects.filter(
        categoria='equipo_disponible',
        titulo__startswith='Equipo listo',
    ).update(requiere_accion=True)


def revertir_equipo_listo_como_accion(apps, schema_editor):
    """Deshace la reclasificación si se revierte la migración."""
    Notificacion = apps.get_model('notificaciones', 'Notificacion')
    Notificacion.objects.filter(
        categoria='equipo_disponible',
        titulo__startswith='Equipo listo',
    ).update(requiere_accion=False)


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0006_notificacion_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='requiere_accion',
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text=(
                    "True: aparece en «Por hacer» y el badge no se apaga al abrir. "
                    "False: aparece en «Avisos» (correo enviado, video listo, etc.)."
                ),
                verbose_name='Requiere acción',
            ),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(
                fields=['usuario', 'requiere_accion', '-fecha_creacion'],
                name='idx_notif_usr_accion_fecha',
            ),
        ),
        migrations.RunPython(
            marcar_equipo_listo_como_accion,
            revertir_equipo_listo_como_accion,
        ),
    ]
