# Generated by Django 5.2.14 on 2026-09-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Solo actualiza help_text de categoria y leida (textos de la campanita).

    No crea columnas nuevas ni cambia datos. Django avisaba en producción
    porque el modelo ya tenía esos textos y la migración 0006/0001 no.
    """

    dependencies = [
        ('notificaciones', '0007_notificacion_requiere_accion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='categoria',
            field=models.CharField(db_index=True, default='general', help_text='Agrupación de dominio para filtros de la campanita (ej. general, equipo_disponible)', max_length=40, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='leida',
            field=models.BooleanField(default=False, help_text='Los avisos informativos se marcan al abrir la campanita. Los que requieren acción se marcan al pulsar el ítem o ✓✓.', verbose_name='Leída'),
        ),
    ]
