# Generated by Django 5.2.14 on 2026-09-28 22:39

import re
import unicodedata

from django.db import migrations, models


def _sin_acentos(texto: str) -> str:
    """Quita tildes para que Satélite y Satelite coincidan."""
    descompuesto = unicodedata.normalize('NFD', texto or '')
    return ''.join(
        caracter
        for caracter in descompuesto
        if unicodedata.category(caracter) != 'Mn'
    )


def _categoria_por_nombre(nombre: str) -> str:
    """
    Misma regla que categoria_por_nombre_sucursal.

    Se copia aquí para que la migración no dependa del código vivo:
    si esa función cambia mañana, este backfill ya quedó aplicado.
    """
    texto = _sin_acentos((nombre or '').lower())
    if 'drop' in texto:
        return 'equipo_disponible_dropoff'
    if 'satelit' in texto:
        return 'equipo_disponible_satelite'
    return 'equipo_disponible'


def reclasificar_equipo_por_sucursal(apps, schema_editor):
    """
    Pasa a Satélite o Drop Off los avisos de garantía que ya nombran la sede.

    EXPLICACIÓN: El texto dice «está lista en {sucursal}». Los de recepción
    (fuera de garantía) no traen esa frase y se quedan en equipo_disponible.
    """
    Notificacion = apps.get_model('notificaciones', 'Notificacion')
    # Paso: la migración corre en cada país; .using() no deja que el router
    # mande todo a la base default.
    alias = schema_editor.connection.alias
    avisos = Notificacion.objects.using(alias).filter(
        categoria='equipo_disponible',
        mensaje__icontains='está lista en',
    )
    ids_dropoff = []
    ids_satelite = []
    for aviso in avisos.iterator():
        coincidencia = re.search(r'está lista en (.+?)\.', aviso.mensaje or '')
        if not coincidencia:
            continue
        # Paso: solo se mueve si el nombre es Drop Off o Satélite.
        nueva = _categoria_por_nombre(coincidencia.group(1))
        if nueva == 'equipo_disponible_dropoff':
            ids_dropoff.append(aviso.pk)
        elif nueva == 'equipo_disponible_satelite':
            ids_satelite.append(aviso.pk)

    if ids_dropoff:
        Notificacion.objects.using(alias).filter(pk__in=ids_dropoff).update(
            categoria='equipo_disponible_dropoff',
        )
    if ids_satelite:
        Notificacion.objects.using(alias).filter(pk__in=ids_satelite).update(
            categoria='equipo_disponible_satelite',
        )


def revertir_equipo_por_sucursal(apps, schema_editor):
    """Devuelve Satélite y Drop Off al filtro general si se revierte."""
    Notificacion = apps.get_model('notificaciones', 'Notificacion')
    alias = schema_editor.connection.alias
    Notificacion.objects.using(alias).filter(
        categoria__in=(
            'equipo_disponible_satelite',
            'equipo_disponible_dropoff',
        ),
    ).update(categoria='equipo_disponible')


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0008_alter_notificacion_categoria_leida_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='categoria',
            field=models.CharField(db_index=True, default='general', help_text='Agrupación de dominio para filtros de la campanita (ej. general, equipo_disponible, equipo_disponible_satelite, equipo_disponible_dropoff)', max_length=40, verbose_name='Categoría'),
        ),
        migrations.RunPython(
            reclasificar_equipo_por_sucursal,
            revertir_equipo_por_sucursal,
        ),
    ]
