# Generated by Django 5.2.14 on 2026-09-28 23:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0009_reclasificar_equipo_por_sucursal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='cumplida',
            field=models.BooleanField(db_index=True, default=False, help_text='True: la tarea ya se hizo y el aviso pasa a «Cumplidas» (verde). Abrir la campanita no marca este campo.', verbose_name='Cumplida'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='fecha_cumplida',
            field=models.DateTimeField(blank=True, help_text='Cuándo se completó la tarea. Vacío mientras sigue en Por hacer.', null=True, verbose_name='Fecha de cumplimiento'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='leida',
            field=models.BooleanField(default=False, help_text='Los avisos informativos se marcan al abrir la campanita. Los que requieren acción se marcan al pulsar el ítem o ✓✓. Abrir no significa que la tarea ya se cumplió.', verbose_name='Leída'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['usuario', 'cumplida', '-fecha_cumplida'], name='idx_notif_usr_cumplida_fecha'),
        ),
    ]
