"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-c^$$m7)o4(**%esnl3ao&z^n&pn3*r=^qxu-!cmczpe#wdi372')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

# Permitir conexiones desde cualquier host para desarrollo (celular, otros dispositivos)
# IMPORTANTE: Cambiar esto en producción por seguridad
ALLOWED_HOSTS = [
    'localhost', 
    '127.0.0.1',
    '192.168.10.244',    # Tu IP actual principal
    '192.168.137.1',     # Tu IP de punto de acceso móvil
    '192.168.10.*',      # Cualquier IP en tu red local principal
    '192.168.137.*',     # Cualquier IP en tu red de punto de acceso
    '192.168.*.*',       # Cualquier IP en redes locales 192.168.x.x
    '10.*.*.*',          # Redes privadas clase A
    '*'                  # Permitir cualquier host (solo para desarrollo)
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'inventario',
    'scorecard',  # Nueva app para Score Card de Calidad
    'servicio_tecnico',  # Nueva app para Gestión de Órdenes de Servicio Técnico
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Middleware personalizado para forzar cambio de contraseña en primer login
    # DEBE estar después de AuthenticationMiddleware (para tener acceso a request.user)
    'inventario.middleware.ForcePasswordChangeMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-mx'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Directorios donde Django buscará archivos estáticos adicionales
STATICFILES_DIRS = [
    BASE_DIR / "static",  # Archivos estáticos globales del proyecto
]

# Directorio donde se recopilarán todos los archivos estáticos en producción
# Descomenta esto para producción:
# STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files (User uploaded content - imágenes de evidencias)
# https://docs.djangoproject.com/en/5.2/topics/files/
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Email Configuration (SMTP)
# https://docs.djangoproject.com/en/5.2/topics/email/
# Configuración para envío de notificaciones de Score Card
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')  # Leer desde .env
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')  # Leer desde .env
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='Score Card System <noreply@example.com>')
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Email del Jefe de Calidad (usado en notificaciones de Score Card)
JEFE_CALIDAD_EMAIL = config('JEFE_CALIDAD_EMAIL', default='calidad@example.com')
JEFE_CALIDAD_NOMBRE = config('JEFE_CALIDAD_NOMBRE', default='Jefe de Calidad')

# Email del Segundo Jefe de Calidad (también recibe copia de todas las notificaciones)
JEFE_CALIDAD_2_EMAIL = config('JEFE_CALIDAD_2_EMAIL', default='')
JEFE_CALIDAD_2_NOMBRE = config('JEFE_CALIDAD_2_NOMBRE', default='Segundo Jefe de Calidad')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication settings
# https://docs.djangoproject.com/en/5.2/topics/auth/default/
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = 'home'  # Redirigir al dashboard después de login
# LOGOUT_REDIRECT_URL removido para mostrar la página de logout personalizada
