"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Crear directorio de logs si no existe (compatible Windows/Linux/Mac)
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-c^$$m7)o4(**%esnl3ao&z^n&pn3*r=^qxu-!cmczpe#wdi372')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

# EXPLICACIÓN: ALLOWED_HOSTS especifica qué dominios/IPs pueden acceder a tu aplicación
# En producción, solo incluye dominios e IPs específicas por seguridad
ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='localhost,127.0.0.1,192.168.1.235',
    cast=lambda v: [s.strip() for s in v.split(',')]
)

# CSRF: Configuración para permitir solicitudes desde dominios externos
# EXPLICACIÓN: Lista de orígenes confiables para solicitudes CSRF (formularios, AJAX)
# Agregar aquí tu dominio cuando tengas HTTPS configurado
CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='http://localhost,http://127.0.0.1,http://192.168.1.235',
    cast=lambda v: [s.strip() for s in v.split(',')]
)

# ============================================================================
# CONFIGURACIONES DE SEGURIDAD PARA PRODUCCIÓN
# ============================================================================
# EXPLICACIÓN PARA PRINCIPIANTES:
# Estas configuraciones protegen tu aplicación cuando está expuesta a Internet
# Solo se activan cuando DEBUG=False (producción)

# HTTPS Strict Transport Security (HSTS)
# Obliga a los navegadores a usar HTTPS durante 1 año (31536000 segundos)
# IMPORTANTE: Solo activar cuando estés 100% seguro de que todo funciona con HTTPS
if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000  # 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Cookies seguras (solo se envían por HTTPS)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # Nota: NO activamos SECURE_SSL_REDIRECT porque Cloudflare maneja la redirección
    # El tráfico entre Cloudflare y Nginx es HTTP, pero el usuario siempre ve HTTPS
    # SECURE_SSL_REDIRECT = False  # Cloudflare ya redirige HTTP → HTTPS
    
    # ── NUEVO (Multi-País): Aislamiento de cookies por subdominio ──
    # EXPLICACIÓN PARA PRINCIPIANTES:
    # Sin esto, tu sesión de Mexico funcionaría en Argentina (inseguro).
    # SESSION_COOKIE_DOMAIN = None → Django usa el Host header del request,
    # así cada subdominio (mexico.sigmasystem.work, argentina.sigmasystem.work)
    # tiene su propia cookie independiente.
    SESSION_COOKIE_DOMAIN = None  # Django usa el Host header del request
    SESSION_COOKIE_NAME = 'sigma_sessionid'
    CSRF_COOKIE_NAME = 'sigma_csrftoken'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'axes',  # Django-Axes: Protección contra ataques de fuerza bruta
    'inventario',
    'scorecard',  # Nueva app para Score Card de Calidad
    'servicio_tecnico',  # Nueva app para Gestión de Órdenes de Servicio Técnico
    'almacen',  # Nueva app para Inventario de Almacén Central - Dic 2025
    'django_celery_beat',  # Celery Beat: tareas programadas (cron jobs)
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Django-Axes: Middleware para detectar y bloquear intentos de fuerza bruta
    'axes.middleware.AxesMiddleware',
    # ┌─────────────────────────────────────────────────────────────┐
    # │ NUEVO (Multi-País): Detecta el país por subdominio          │
    # │ DEBE ir DESPUÉS de AuthenticationMiddleware                  │
    # │ DEBE ir ANTES de ForcePasswordChangeMiddleware               │
    # │                                                              │
    # │ ¿POR QUÉ este orden?                                        │
    # │ 1. AuthenticationMiddleware pone request.user                │
    # │ 2. PaisMiddleware configura la BD del país                   │
    # │ 3. ForcePasswordChangeMiddleware consulta request.user.empleado │
    # │    (necesita que el router ya sepa la BD correcta)           │
    # └─────────────────────────────────────────────────────────────┘
    'config.middleware_pais.PaisMiddleware',
    # Forzar cambio de contraseña en primer login
    'inventario.middleware.ForcePasswordChangeMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # NUEVO (Multi-País): Variables de país en todos los templates
                'config.context_processors.pais_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# ============================================================================
# CONFIGURACIÓN DE BASE DE DATOS (Multi-País)
# ============================================================================
# 
# EXPLICACIÓN PARA PRINCIPIANTES:
# Antes teníamos UNA sola base de datos ('default').
# Ahora tenemos una BD por país, pero Django necesita saber
# cómo conectarse a cada una.
#
# 'default' siempre apunta a México (el país principal).
# 'mexico' es un ALIAS que apunta a la misma BD que 'default'.
# 'argentina' apunta a la BD de Argentina.
#
# ¿POR QUÉ 'default' y 'mexico' apuntan a lo mismo?
# Porque manage.py y migrations siempre usan 'default'.
# Si 'default' no existiera, Django fallaría al iniciar.

DB_ENGINE = config('DB_ENGINE', default='django.db.backends.postgresql')

# Determinar si estamos en SQLite (desarrollo) o PostgreSQL (producción)
_is_sqlite = 'sqlite3' in DB_ENGINE

# --- Configuración para producción (PostgreSQL) ---
if not _is_sqlite:
    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME': config('DB_NAME', default='inventario_mexico'),
            'USER': config('DB_USER', default='django_user'),
            'PASSWORD': config('DB_PASSWORD', default=''),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='5432'),
            'CONN_MAX_AGE': 600,
            'OPTIONS': {'connect_timeout': 10},
        },
        'mexico': {
            'ENGINE': DB_ENGINE,
            'NAME': config('DB_NAME', default='inventario_mexico'),
            'USER': config('DB_USER', default='django_user'),
            'PASSWORD': config('DB_PASSWORD', default=''),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='5432'),
            'CONN_MAX_AGE': 600,
            'OPTIONS': {'connect_timeout': 10},
        },
        'argentina': {
            'ENGINE': DB_ENGINE,
            'NAME': config('DB_NAME_AR', default='inventario_argentina'),
            'USER': config('DB_USER', default='django_user'),
            'PASSWORD': config('DB_PASSWORD', default=''),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='5432'),
            'CONN_MAX_AGE': 600,
            'OPTIONS': {'connect_timeout': 10},
        },
    }

# --- Configuración para desarrollo (SQLite) ---
else:
    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME': BASE_DIR / config('DB_NAME', default='db.sqlite3'),
        },
        'mexico': {
            'ENGINE': DB_ENGINE,
            'NAME': BASE_DIR / config('DB_NAME', default='db.sqlite3'),
        },
        'argentina': {
            'ENGINE': DB_ENGINE,
            'NAME': BASE_DIR / config('DB_NAME_AR', default='db_argentina.sqlite3'),
        },
    }

# ============================================================================
# DATABASE ROUTER (Multi-País)
# ============================================================================
# 
# EXPLICACIÓN PARA PRINCIPIANTES:
# Django consulta estos routers para cada query de base de datos.
# Nuestro router redirige las queries a la BD del país activo.
# Si no hay país activo (manage.py, shell), usa 'default' (México).

DATABASE_ROUTERS = ['config.db_router.PaisDBRouter']


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# ============================================================================
# INTERNACIONALIZACIÓN (Multi-País)
# ============================================================================
#
# NOTA: TIME_ZONE y LANGUAGE_CODE aquí son los DEFAULTS del servidor.
# La zona horaria real se aplica por request usando pais_config['timezone'].
# Ver: config/paises_config.py → fecha_local_pais()

LANGUAGE_CODE = 'es-mx'  # Default del servidor (se puede override por país)

TIME_ZONE = 'UTC'  # CAMBIO v2.0: Usar UTC como zona del servidor
                    # Las fechas se convierten a local en las vistas
                    # usando fecha_local_pais() de paises_config.py

USE_I18N = True

USE_TZ = True  # IMPORTANTE: Mantener True para que Django guarde en UTC


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Directorios donde Django buscará archivos estáticos adicionales
# EXPLICACIÓN: STATICFILES_DIRS contiene las carpetas con tus archivos originales (CSS, JS, imágenes)
STATICFILES_DIRS = [
    BASE_DIR / "static",  # Archivos estáticos globales del proyecto
]

# Directorio donde se recopilarán todos los archivos estáticos en producción
# EXPLICACIÓN: STATIC_ROOT es donde Django copia TODOS los archivos estáticos
# para que el servidor web (Nginx) los pueda servir eficientemente
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files (User uploaded content - imágenes de evidencias)
# https://docs.djangoproject.com/en/5.2/topics/files/
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ============================================================================
# CONFIGURACIÓN DE ALMACENAMIENTO DINÁMICO (DISCO ALTERNO)
# ============================================================================
# Usar el storage dinámico que cambia automáticamente entre disco C: y D:
# según el espacio disponible
#
# EXPLICACIÓN PARA PRINCIPIANTES:
# Django 5.x usa el dict STORAGES para configurar almacenamiento
# 'default' = storage para archivos subidos por usuarios (ImageField, FileField)
# 'staticfiles' = storage para archivos estáticos (CSS, JS)
STORAGES = {
    "default": {
        "BACKEND": "config.storage_utils.DynamicFileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# ============================================================================
# CONFIGURACIÓN DE LÍMITES DE CARGA DE ARCHIVOS
# ============================================================================
# Configurado para soportar múltiples imágenes de alta resolución desde celulares
# Límite alineado con Cloudflare Free (100MB max por request)
# Ejemplo: 30 imágenes de 3MB c/u = 90MB total
DATA_UPLOAD_MAX_MEMORY_SIZE = 95 * 1024 * 1024  # 95MB total por request (múltiples archivos)
FILE_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024   # 50MB por archivo individual

# Directorio temporal para uploads
# EXPLICACIÓN PARA PRINCIPIANTES:
# Django necesita un lugar donde guardar archivos temporales durante la subida.
# Por defecto usa /tmp, pero en producción con Gunicorn+systemd esto causa problemas
# porque cada worker tiene su propio namespace /tmp privado que puede corromperse.
#
# Solución: Usar un directorio dedicado (/var/www/django_temp) configurado vía .env
# 
# PRODUCCIÓN: USE_CUSTOM_TEMP_DIR=True  → usa /var/www/django_temp
# DESARROLLO: USE_CUSTOM_TEMP_DIR=False → usa /tmp del sistema (None = auto)
USE_CUSTOM_TEMP_DIR = config('USE_CUSTOM_TEMP_DIR', default=False, cast=bool)

if USE_CUSTOM_TEMP_DIR:
    # Producción: Directorio dedicado en /var/www con 430GB de espacio
    # Esto evita problemas de "FileNotFoundError" cuando los workers de Gunicorn
    # intentan acceder a archivos temporales en namespaces corruptos por systemd
    FILE_UPLOAD_TEMP_DIR = '/var/www/django_temp'
else:
    # Desarrollo: Usa el directorio temporal del sistema (/tmp en Linux, %TEMP% en Windows)
    FILE_UPLOAD_TEMP_DIR = None  # Django usará tempfile.gettempdir() automáticamente

# Límite de campos por request (incluye archivos múltiples)
# Configurado para soportar hasta 50 archivos simultáneos + campos del formulario
# Valor por defecto de Django: 1000
DATA_UPLOAD_MAX_NUMBER_FIELDS = 2000  # Permite múltiples archivos sin problemas

# Email Configuration (SMTP)
# https://docs.djangoproject.com/en/5.2/topics/email/
# Configuración para envío de notificaciones de Score Card
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')  # Leer desde .env
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')  # Leer desde .env
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='Score Card System <noreply@example.com>')
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Email del Jefe de Calidad (usado en notificaciones de Score Card)
JEFE_CALIDAD_EMAIL = config('JEFE_CALIDAD_EMAIL', default='calidad@example.com')
JEFE_CALIDAD_NOMBRE = config('JEFE_CALIDAD_NOMBRE', default='Jefe de Calidad')

# Email del Segundo Jefe de Calidad (también recibe copia de todas las notificaciones)
JEFE_CALIDAD_2_EMAIL = config('JEFE_CALIDAD_2_EMAIL', default='')
JEFE_CALIDAD_2_NOMBRE = config('JEFE_CALIDAD_2_NOMBRE', default='Segundo Jefe de Calidad')

# ============================================================================
# CONFIGURACIÓN DE CORREOS PARA SERVICIO TÉCNICO - RHITSO
# ============================================================================
# Destinatarios principales para envío de equipos a RHITSO
# Estos correos se leen desde .env por seguridad
# Estructura: cada contacto tiene nombre y email configurables

def _build_rhitso_recipients():
    """
    Función auxiliar para construir la lista de destinatarios RHITSO desde .env
    
    EXPLICACIÓN PARA PRINCIPIANTES:
    Esta función lee las variables de entorno del archivo .env y construye
    una lista de diccionarios con los destinatarios de RHITSO.
    Solo incluye contactos que tengan email configurado (no vacío).
    """
    recipients = []
    # Iteramos sobre 4 posibles contactos (puedes agregar más si necesitas)
    for i in range(1, 5):
        nombre = config(f'RHITSO_CONTACTO_{i}_NOMBRE', default='')
        email = config(f'RHITSO_CONTACTO_{i}_EMAIL', default='')
        
        # Solo agregar si el email está configurado
        if email:
            recipients.append({
                'nombre': nombre,
                'email': email,
                'grupo': 'rhitso_principal',
                'descripcion': f'Contacto {i} RHITSO'
            })
    
    return recipients

# Lista de destinatarios RHITSO generada dinámicamente desde .env
RHITSO_EMAIL_RECIPIENTS = _build_rhitso_recipients()

# Áreas de empleados que pueden recibir copia de notificaciones RHITSO
# Los empleados de estas áreas aparecerán en la sección "Con copia a:" del modal
# La búsqueda es case-insensitive (no distingue mayúsculas/minúsculas)
RHITSO_AREAS_COPIA = ['CALIDAD', 'FRONTDESK', 'COMPRAS']

# Email del Jefe General (también recibe copia de todas las notificaciones)
JEFE_GENERAL_EMAIL = config('JEFE_GENERAL_EMAIL', default='')
JEFE_GENERAL_NOMBRE = config('JEFE_GENERAL_NOMBRE', default='Jefe General')

# Email del Ayudante de Compras (también recibe copia de todas las notificaciones)
AYUDANTE_COMPRAS_EMAIL = config('AYUDANTE_COMPRAS_EMAIL', default='')
AYUDANTE_COMPRAS_NOMBRE = config('AYUDANTE_COMPRAS_NOMBRE', default='Ayudante Compras')

# ============================================================================
# CONFIGURACIÓN DE CELERY (Tareas en Segundo Plano)
# ============================================================================
#
# EXPLICACIÓN PARA PRINCIPIANTES:
# Celery permite ejecutar tareas pesadas SIN bloquear al usuario.
# Ejemplos en este proyecto:
#   - Enviar emails de RHITSO (sin que el usuario espere)
#   - Generar PDFs/Excels grandes en background
#   - Pre-calcular datos del dashboard de analytics
#   - Predicciones de ML al recibir una orden nueva
#
# Redis actúa como puente: Django deposita tareas en Redis,
# el Worker de Celery las lee y las ejecuta.

# URL del broker de mensajes (Redis)
# En desarrollo: Redis corre localmente en el puerto 6379
# El '/0' al final significa 'base de datos 0' (Redis tiene 16 BD numeradas)
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://localhost:6379/0')

# Dónde guardar los RESULTADOS de las tareas (también Redis, BD 1)
# Útil para saber si una tarea terminó bien o falló
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://localhost:6379/1')

# Formato de serialización de datos (JSON es el más seguro y legible)
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']

# Zona horaria de Celery (usa la misma que Django)
CELERY_TIMEZONE = TIME_ZONE

# MODO SÍNCRONO EN DESARROLLO (sin Worker activo)
# EXPLICACIÓN: Si CELERY_TASK_ALWAYS_EAGER=True, las tareas se ejecutan
# de forma inmediata y síncrona, como si Celery no existiera.
# Útil para testing o cuando no tienes el Worker corriendo.
# En este proyecto está en False porque SÍ tenemos Redis instalado.
CELERY_TASK_ALWAYS_EAGER = config('CELERY_TASK_ALWAYS_EAGER', default=False, cast=bool)

# Tiempo máximo que una tarea puede tardar antes de ser cancelada (segundos)
# Evita tareas colgadas que bloqueen el Worker indefinidamente
CELERY_TASK_SOFT_TIME_LIMIT = 300   # 5 minutos: aviso de timeout
CELERY_TASK_TIME_LIMIT = 600        # 10 minutos: cancelación forzada

# Número de reintentos automáticos si una tarea falla
CELERY_TASK_MAX_RETRIES = 3

# Guardar resultados de tareas en la base de datos (para django-celery-beat)
CELERY_RESULT_EXPIRES = 60 * 60 * 24  # Resultados se eliminan tras 24 horas

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication settings
# https://docs.djangoproject.com/en/5.2/topics/auth/default/
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = 'home'  # Redirigir al dashboard después de login
# LOGOUT_REDIRECT_URL removido para mostrar la página de logout personalizada

# ============================================================================
# CONFIGURACIÓN DE LOGGING (Registros de Errores y Debug)
# ============================================================================
# EXPLICACIÓN PARA PRINCIPIANTES:
# El sistema de logging registra todos los eventos importantes del sistema:
# - Errores 500 (Internal Server Error)
# - Consultas SQL lentas
# - Advertencias del sistema
# - Información de depuración
#
# Los logs se guardan en archivos que puedes revisar cuando algo falla

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'console_safe': {
            # Formateador SEGURO para consola Windows (sin emojis)
            '()': 'config.logging_formatters.ConsoleFormatter',
            'format': '[{levelname}] {asctime} {name} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'verbose': {
            # Formateador para archivos UTF-8 (preserva emojis)
            'format': '[{levelname}] {asctime} {name} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'console_safe',  # Usa formateador que elimina emojis
            # SOLUCIÓN WINDOWS: ConsoleFormatter reemplaza emojis por texto ASCII
            # Evita UnicodeEncodeError en consola Windows (cp1252)
        },
        'file_errors': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'django_errors.log',
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',  # UTF-8 para soportar emojis y caracteres especiales
        },
        'file_debug': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'django_debug.log',
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 3,
            'formatter': 'verbose',
            'filters': ['require_debug_true'],
            'encoding': 'utf-8',  # UTF-8 para soportar emojis y caracteres especiales
        },
        'file_db': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'django_db.log',
            'maxBytes': 5 * 1024 * 1024,  # 5 MB
            'backupCount': 3,
            'formatter': 'verbose',
            'encoding': 'utf-8',  # UTF-8 para soportar emojis y caracteres especiales
        },
    },
    'loggers': {
        # Logger principal de Django - captura todos los errores
        'django': {
            'handlers': ['console', 'file_errors'],
            'level': 'INFO',
            'propagate': False,
        },
        # Logger de peticiones HTTP - captura errores 500, 404, etc.
        'django.request': {
            'handlers': ['console', 'file_errors'],
            'level': 'ERROR',
            'propagate': False,
        },
        # Logger de base de datos - captura consultas SQL (solo en DEBUG)
        'django.db.backends': {
            'handlers': ['file_db'],
            'level': 'WARNING',  # Cambiar a DEBUG para ver todas las consultas SQL
            'propagate': False,
        },
        # Logger para tu aplicación - captura errores de tu código
        'inventario': {
            'handlers': ['console', 'file_errors', 'file_debug'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'scorecard': {
            'handlers': ['console', 'file_errors', 'file_debug'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'servicio_tecnico': {
            'handlers': ['console', 'file_errors', 'file_debug'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console', 'file_errors'],
        'level': 'INFO',
    },
}

# ============================================================================
# CONFIGURACIÓN DE DJANGO-AXES (Protección contra Fuerza Bruta)
# ============================================================================
# EXPLICACIÓN PARA PRINCIPIANTES:
# Django-Axes protege tu aplicación bloqueando intentos repetidos de login
# desde la misma IP o usuario después de cierto número de intentos fallidos.

# Backend de autenticación - debe incluir AxesBackend
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',  # Django-Axes backend (DEBE ir primero)
    'django.contrib.auth.backends.ModelBackend',  # Backend por defecto de Django
]

# Configuración de bloqueo
AXES_FAILURE_LIMIT = 5  # Número de intentos fallidos antes de bloquear (5 intentos)
AXES_COOLOFF_TIME = 1  # Tiempo de bloqueo en horas (1 hora)

# Configuración actualizada (versión 8.1.0)
# Bloquea por combinación de usuario + IP (más seguro que solo IP o solo usuario)
AXES_LOCKOUT_PARAMETERS = [['username', 'ip_address']]

# Configuración de reset y limpieza
AXES_RESET_ON_SUCCESS = True  # Reinicia contador después de login exitoso
AXES_LOCKOUT_TEMPLATE = None  # Usa mensaje por defecto de Django (403 Forbidden)

# Logging de intentos
AXES_VERBOSE = True  # Registra intentos de acceso en logs

# IP Whitelisting (opcional - descomentarlo si necesitas permitir IPs específicas)
# AXES_NEVER_LOCKOUT_WHITELIST = True
# AXES_IP_WHITELIST = ['127.0.0.1', '192.168.100.22']  # IPs que nunca se bloquean
