# Generated by Django 5.2.5 on 2025-10-07 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_tecnico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleequipo',
            name='orden_cliente',
            field=models.CharField(blank=True, db_index=True, help_text='Número de orden del cliente (identificador interno del cliente)', max_length=50),
        ),
    ]
