# Generated by Django 5.2.5 on 2025-10-07 06:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_tecnico', '0002_detalleequipo_orden_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenorden',
            name='imagen_original',
            field=models.ImageField(blank=True, help_text='Archivo de imagen original sin comprimir (alta resolución)', null=True, upload_to='servicio_tecnico/imagenes_originales/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='imagenorden',
            name='imagen',
            field=models.ImageField(help_text='Archivo de imagen comprimida para galería (JPG, PNG, GIF)', upload_to='servicio_tecnico/imagenes/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='imagenorden',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso - Estado Inicial'), ('diagnostico', 'Durante Diagnóstico'), ('reparacion', 'Durante Reparación'), ('egreso', 'Egreso - Estado Final'), ('otras', 'Otras')], help_text='Tipo de imagen (ingreso, egreso, diagnóstico, etc.)', max_length=15),
        ),
    ]
