# Generated by Django 5.2.5 on 2025-10-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_tecnico', '0003_imagenorden_imagen_original_alter_imagenorden_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientopieza',
            name='piezas',
            field=models.ManyToManyField(blank=True, help_text='Piezas específicas que se están rastreando en este pedido', related_name='seguimientos', to='servicio_tecnico.piezacotizada'),
        ),
    ]
