# Generated by Django 5.2.5 on 2025-10-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_tecnico', '0005_ordenservicio_control_calidad_requerido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenservicio',
            name='monto_abono_previo',
        ),
        migrations.RemoveField(
            model_name='ordenservicio',
            name='notas_conversion',
        ),
        migrations.RemoveField(
            model_name='ordenservicio',
            name='orden_venta_mostrador_previa',
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='estado',
            field=models.CharField(choices=[('espera', 'En Espera'), ('recepcion', 'En Recepción'), ('diagnostico', 'En Diagnóstico'), ('cotizacion', 'Esperando Aprobación Cliente'), ('rechazada', 'Cotización Rechazada'), ('esperando_piezas', 'Esperando Llegada de Piezas'), ('reparacion', 'En Reparación'), ('control_calidad', 'Control de Calidad'), ('finalizado', 'Finalizado - Listo para Entrega'), ('entregado', 'Entregado al Cliente'), ('cancelado', 'Cancelado')], default='espera', help_text='Estado actual de la orden', max_length=30),
        ),
    ]
