# Generated by Django 5.2.5 on 2025-10-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_tecnico', '0007_categoriadiagnostico_configuracionrhitso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientorhitso',
            name='es_cambio_automatico',
            field=models.BooleanField(default=False, help_text='True si el cambio fue generado automáticamente por el sistema (signals), False si fue manual (usuario)'),
        ),
    ]
