# Generated by Django 5.2.5 on 2025-10-15 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_tecnico', '0008_agregar_campo_es_cambio_automatico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenservicio',
            name='estado',
            field=models.CharField(choices=[('espera', 'En Espera'), ('recepcion', 'En Recepción'), ('diagnostico', 'En Diagnóstico'), ('equipo_diagnosticado', 'Equipo Diagnosticado'), ('diagnostico_enviado_cliente', 'Diagnóstico Enviado al Cliente'), ('cotizacion_enviada_proveedor', 'Envío de Cotización al Proveedor'), ('cotizacion_recibida_proveedor', 'Se Recibe Cotización de Proveedores'), ('cotizacion', 'Esperando Aprobación Cliente'), ('cliente_acepta_cotizacion', 'Cliente Acepta Cotización'), ('rechazada', 'Cotización Rechazada'), ('partes_solicitadas_proveedor', 'Partes Solicitadas a Proveedor'), ('esperando_piezas', 'Esperando Llegada de Piezas'), ('piezas_recibidas', 'Piezas Recibidas'), ('wpb_pieza_incorrecta', 'WPB - Pieza Incorrecta'), ('doa_pieza_danada', 'DOA - Pieza Dañada'), ('pnc_parte_no_disponible', 'PNC - Parte No Disponible'), ('reparacion', 'En Reparación'), ('control_calidad', 'Control de Calidad'), ('finalizado', 'Finalizado - Listo para Entrega'), ('entregado', 'Entregado al Cliente'), ('cancelado', 'Cancelado')], default='espera', help_text='Estado actual de la orden', max_length=30),
        ),
    ]
