# Generated by Django 5.2.5 on 2025-10-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_tecnico', '0009_agregar_nuevos_estados_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='descontar_mano_obra',
            field=models.BooleanField(default=False, help_text='¿Se descuenta la mano de obra como beneficio por aceptar la cotización?'),
        ),
    ]
