# Generated by Django 5.2.5 on 2025-11-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_tecnico', '0011_alter_cotizacion_motivo_rechazo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='motivo_rechazo',
            field=models.CharField(blank=True, choices=[('costo_alto', 'Costo muy elevado'), ('muchas_piezas', 'Demasiadas piezas a cambiar'), ('tiempo_largo', 'Tiempo de reparación muy largo'), ('falta_justificacion', 'Falta de justificación en diagnóstico'), ('no_vale_pena', 'No vale la pena reparar'), ('no_hay_partes', 'No hay partes en el mercado'), ('solo_venta_mostrador', 'Solo está interesado en la propuesta de venta mostrador'), ('falta_de_respuesta', 'Se cierra cotización por vigencia y falta de respuesta del cliente'), ('no_apto', 'Equipo no apto para diagnóstico o reparación'), ('rechazo_sin_decision', 'Cliente desea evaluar las opciones sin tomar decisión inmediata'), ('otro', 'Otro motivo')], help_text='Motivo por el cual rechazó la cotización', max_length=30),
        ),
        migrations.AlterField(
            model_name='detalleequipo',
            name='marca',
            field=models.CharField(choices=[('', '-- Seleccione una marca --'), ('acer', 'Acer'), ('apple', 'Apple'), ('asus', 'Asus'), ('compaq', 'Compaq'), ('dell', 'Dell'), ('gateway', 'Gateway'), ('hp', 'HP'), ('huawei', 'Huawei'), ('lenovo', 'Lenovo'), ('msi', 'MSI'), ('samsung', 'Samsung'), ('sony', 'Sony'), ('toshiba', 'Toshiba'), ('otra', 'Otra Marca')], help_text='Marca del equipo (selecciona de la lista)', max_length=50),
        ),
        migrations.AlterField(
            model_name='seguimientopieza',
            name='estado',
            field=models.CharField(choices=[('pedido', 'Pedido Realizado'), ('confirmado', 'Pedido Confirmado'), ('transito', 'En Tránsito'), ('retrasado', 'Retrasado'), ('recibido', 'Recibido en Sucursal'), ('incorrecto', 'WPB - Pieza Incorrecta'), ('danado', 'DOA - Pieza Dañada/No Funcional')], default='pedido', help_text='Estado actual del pedido', max_length=15),
        ),
    ]
