# Generated by Django 5.2.5 on 2025-11-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_tecnico', '0012_agregar_estados_pieza_problematica'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleequipo',
            name='email_cliente',
            field=models.EmailField(default='cliente@ejemplo.com', help_text='Email del cliente para envío de fotos y notificaciones', max_length=254),
        ),
    ]
