# Generated by Django 5.2.5 on 2025-11-13 18:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_tecnico', '0014_cambiar_estructura_imagenes_por_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventamostrador',
            name='costo_respaldo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo del servicio de respaldo de información', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='ventamostrador',
            name='incluye_respaldo',
            field=models.BooleanField(default=False, help_text='¿Incluye respaldo de información del cliente?'),
        ),
    ]
