# Generated by Django 5.2.5 on 2025-11-13 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_tecnico', '0015_ventamostrador_costo_respaldo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='piezacotizada',
            name='proveedor',
            field=models.CharField(blank=True, default='', help_text='Proveedor con el cual se cotizó esta pieza (opcional)', max_length=100),
        ),
    ]
