# Generated by Django 5.2.5 on 2025-11-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_tecnico', '0016_piezacotizada_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleequipo',
            name='marca',
            field=models.CharField(choices=[('', '-- Seleccione una marca --'), ('Acer', 'Acer'), ('Apple', 'Apple'), ('Asus', 'Asus'), ('Compaq', 'Compaq'), ('Dell', 'Dell'), ('Gateway', 'Gateway'), ('HP', 'HP'), ('Huawei', 'Huawei'), ('Lenovo', 'Lenovo'), ('MSI', 'MSI'), ('Samsung', 'Samsung'), ('Sony', 'Sony'), ('Toshiba', 'Toshiba'), ('Otra', 'Otra Marca')], help_text='Marca del equipo (selecciona de la lista)', max_length=50),
        ),
        migrations.AlterField(
            model_name='historialorden',
            name='estado_anterior',
            field=models.CharField(blank=True, help_text='Estado anterior (si aplica)', max_length=30),
        ),
        migrations.AlterField(
            model_name='historialorden',
            name='estado_nuevo',
            field=models.CharField(blank=True, help_text='Estado nuevo (si aplica)', max_length=30),
        ),
    ]
