# Generated by Django 5.2.8 on 2025-12-03 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_tecnico', '0017_alter_detalleequipo_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='motivo_rechazo',
            field=models.CharField(blank=True, choices=[('costo_alto', 'Costo muy elevado'), ('muchas_piezas', 'Demasiadas piezas a cambiar'), ('tiempo_largo', 'Tiempo de reparación muy largo'), ('falta_justificacion', 'Falta de justificación en diagnóstico'), ('no_vale_pena', 'No vale la pena reparar'), ('no_hay_partes', 'No hay partes en el mercado'), ('solo_venta_mostrador', 'Solo está interesado en la propuesta de venta mostrador'), ('falta_de_respuesta', 'Se cierra cotización por vigencia y falta de respuesta del cliente'), ('no_apto', 'Equipo no apto para diagnóstico o reparación'), ('rechazo_sin_decision', 'Cliente desea evaluar las opciones sin tomar decisión inmediata'), ('no_especifica_motivo', 'Cliente no especifica motivo, únicamente rechaza la cotización'), ('otro', 'Otro motivo')], help_text='Motivo por el cual rechazó la cotización', max_length=30),
        ),
    ]
