# Generated by Django 5.2.8 on 2025-12-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_tecnico', '0018_alter_cotizacion_motivo_rechazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleequipo',
            name='tipo_equipo',
            field=models.CharField(choices=[('PC', 'PC'), ('Laptop', 'Laptop'), ('AIO', 'AIO (All-in-One)')], help_text='Tipo de equipo (PC, Laptop, AIO)', max_length=10),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='estado',
            field=models.CharField(choices=[('almacen', 'Proveniente de Almacén'), ('espera', 'En Espera'), ('recepcion', 'En Recepción'), ('diagnostico', 'En Diagnóstico'), ('equipo_diagnosticado', 'Equipo Diagnosticado'), ('diagnostico_enviado_cliente', 'Diagnóstico Enviado al Cliente'), ('cotizacion_enviada_proveedor', 'Envío de Cotización al Proveedor'), ('cotizacion_recibida_proveedor', 'Se Recibe Cotización de Proveedores'), ('cotizacion', 'Esperando Aprobación Cliente'), ('cliente_acepta_cotizacion', 'Cliente Acepta Cotización'), ('rechazada', 'Cotización Rechazada'), ('partes_solicitadas_proveedor', 'Partes Solicitadas a Proveedor'), ('esperando_piezas', 'Esperando Llegada de Piezas'), ('piezas_recibidas', 'Piezas Recibidas'), ('wpb_pieza_incorrecta', 'WPB - Pieza Incorrecta'), ('doa_pieza_danada', 'DOA - Pieza Dañada'), ('pnc_parte_no_disponible', 'PNC - Parte No Disponible'), ('reparacion', 'En Reparación'), ('control_calidad', 'Control de Calidad'), ('finalizado', 'Finalizado - Listo para Entrega'), ('entregado', 'Entregado al Cliente'), ('cancelado', 'Cancelado')], default='espera', help_text='Estado actual de la orden', max_length=30),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='motivo_rhitso',
            field=models.CharField(blank=True, choices=[('reballing', 'Requiere Reballing de GPU/CPU'), ('soldadura', 'Soldadura especializada en placa'), ('componente_smd', 'Reemplazo de componentes SMD'), ('corrosion', 'Corrosión severa en placa'), ('cortocircuito', 'Cortocircuito en circuitería'), ('diagnostico_profundo', 'Requiere diagnóstico más profundo'), ('no_hay_piezas', 'No hay partes en el mercado'), ('otro', 'Otro motivo especializado')], help_text='Motivo por el cual se considera para RHITSO', max_length=30),
        ),
    ]
