# Generated by Django 5.2.5 on 2025-12-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_tecnico', '0019_alter_detalleequipo_tipo_equipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleequipo',
            name='marca',
            field=models.CharField(choices=[('', '-- Seleccione una marca --'), ('Acer', 'Acer'), ('Apple', 'Apple'), ('Asus', 'Asus'), ('Compaq', 'Compaq'), ('Dell', 'Dell'), ('Gateway', 'Gateway'), ('Gigabyte', 'Gigabyte'), ('HP', 'HP'), ('Huawei', 'Huawei'), ('Lenovo', 'Lenovo'), ('MSI', 'MSI'), ('Samsung', 'Samsung'), ('Sony', 'Sony'), ('Toshiba', 'Toshiba'), ('Otra', 'Otra Marca')], help_text='Marca del equipo (selecciona de la lista)', max_length=50),
        ),
    ]
