# Generated by Django 5.2.5 on 2026-01-24 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_tecnico', '0020_solicitud_cotizacion_multiproveedor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordenservicio',
            options={'ordering': ['-fecha_ingreso'], 'permissions': [('view_dashboard_gerencial', 'Puede ver dashboards gerenciales (OOW/FL, Cotizaciones)'), ('view_dashboard_seguimiento', 'Puede ver dashboard de seguimiento de piezas')], 'verbose_name': 'Orden de Servicio', 'verbose_name_plural': 'Órdenes de Servicio'},
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='motivo_rechazo',
            field=models.CharField(blank=True, choices=[('costo_alto', 'Costo muy elevado'), ('muchas_piezas', 'Demasiadas piezas a cambiar'), ('tiempo_largo', 'Tiempo de reparación muy largo'), ('falta_justificacion', 'Falta de justificación en diagnóstico'), ('no_vale_pena', 'No vale la pena reparar'), ('no_hay_partes', 'No hay partes en el mercado'), ('solo_venta_mostrador', 'Solo está interesado en la propuesta de venta mostrador'), ('falta_de_respuesta', 'Se cierra cotización por vigencia y falta de respuesta del cliente'), ('no_apto', 'Equipo no apto para diagnóstico o reparación'), ('rechazo_sin_decision', 'Cliente desea evaluar las opciones sin tomar decisión inmediata'), ('no_especifica_motivo', 'Cliente no especifica motivo, únicamente rechaza la cotización'), ('no_autorizado_por_empresa', 'Cliente informa que su empresa no autoriza la reparación'), ('otro', 'Otro motivo')], help_text='Motivo por el cual rechazó la cotización', max_length=30),
        ),
        migrations.AlterField(
            model_name='detalleequipo',
            name='tipo_equipo',
            field=models.CharField(choices=[('', '-- Seleccione un tipo de equipo --'), ('PC', 'PC'), ('Laptop', 'Laptop'), ('AIO', 'AIO (All-in-One)')], help_text='Tipo de equipo (PC, Laptop, AIO)', max_length=10),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='motivo_rhitso',
            field=models.CharField(blank=True, choices=[('reballing', 'Requiere Reballing de GPU/CPU'), ('soldadura', 'Soldadura especializada en placa'), ('componente_smd', 'Reemplazo de componentes SMD'), ('corrosion', 'Corrosión severa en placa'), ('cortocircuito', 'Cortocircuito en circuitería'), ('diagnostico_profundo', 'Requiere diagnóstico más profundo'), ('no_hay_piezas', 'No hay partes en el mercado'), ('daño_profundo_mobo', 'Daño profundo en placa madre'), ('sin_POST', 'No cumple protocolo POST básico'), ('otro', 'Otro motivo especializado')], help_text='Motivo por el cual se considera para RHITSO', max_length=30),
        ),
    ]
