# Generated by Django 5.2.5 on 2026-02-11 19:36

import django.core.validators
import servicio_tecnico.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_tecnico', '0021_add_dashboard_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenorden',
            name='imagen',
            field=models.ImageField(help_text='Archivo de imagen comprimida para galería (JPG, PNG, GIF)', max_length=255, upload_to=servicio_tecnico.models.imagen_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='imagenorden',
            name='imagen_original',
            field=models.ImageField(blank=True, help_text='Archivo de imagen original sin comprimir (alta resolución)', max_length=255, null=True, upload_to=servicio_tecnico.models.imagen_original_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
