# Generated by Django 5.2.5 on 2026-02-24 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_tecnico', '0022_alter_imagenorden_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleequipo',
            name='es_mis',
            field=models.BooleanField(default=False, help_text='¿El equipo llegó por paquetería (Mail-In Service / MIS)?'),
        ),
    ]
