# Generated by Django 5.2.5 on 2026-03-10 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_agregar_numero_whatsapp_empleado'),
        ('servicio_tecnico', '0023_add_es_mis_to_detalleequipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='Token firmado generado con TimestampSigner. Válido por 7 días.', max_length=512, unique=True, verbose_name='Token de acceso')),
                ('tipo', models.CharField(choices=[('rechazo', 'Rechazo de Cotización'), ('satisfaccion', 'Encuesta de Satisfacción')], default='rechazo', max_length=20, verbose_name='Tipo de feedback')),
                ('motivo_rechazo_snapshot', models.CharField(blank=True, help_text='Copia del motivo de rechazo al momento de crear el token', max_length=50, verbose_name='Snapshot del motivo de rechazo')),
                ('comentario_cliente', models.TextField(blank=True, help_text='Explicación libre del cliente sobre por qué rechazó (máx. 1000 chars)', max_length=1000, verbose_name='Comentario del cliente')),
                ('calificacion_general', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Calificación general (1-5 estrellas)')),
                ('calificacion_atencion', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Calificación atención al cliente (1-5 estrellas)')),
                ('calificacion_tiempo', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Calificación tiempo de respuesta (1-5 estrellas)')),
                ('recomienda', models.BooleanField(blank=True, null=True, verbose_name='¿Recomendaría el servicio? (pulgar arriba/abajo)')),
                ('nps', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='NPS: ¿Del 0 al 10, qué tan probable es que nos recomiende?')),
                ('utilizado', models.BooleanField(default=False, help_text='True cuando el cliente ya envió su feedback', verbose_name='Token utilizado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación del token')),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha en que el cliente respondió')),
                ('ip_respuesta', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP del cliente al responder')),
                ('correo_enviado', models.BooleanField(default=False, help_text='Se actualiza a True cuando la tarea Celery envía el correo exitosamente', verbose_name='¿Correo enviado al cliente?')),
                ('cotizacion', models.ForeignKey(help_text='Cotización a la que pertenece este feedback', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='servicio_tecnico.cotizacion', verbose_name='Cotización')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks_enviados', to='inventario.empleado', verbose_name='Enviado por (empleado)')),
            ],
            options={
                'verbose_name': 'Feedback de Cliente',
                'verbose_name_plural': 'Feedbacks de Clientes',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
