# Generated by Django 5.2.5 on 2026-03-11 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_tecnico', '0024_add_feedbackcliente_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenorden',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso - Estado Inicial'), ('diagnostico', 'Durante Diagnóstico'), ('reparacion', 'Durante Reparación'), ('egreso', 'Egreso - Estado Final'), ('autorizacion', 'Autorización/Pass - RHITSO'), ('packing', 'Imágenes Packing')], help_text='Tipo de imagen (ingreso, egreso, diagnóstico, etc.)', max_length=15),
        ),
    ]
