# Generated by Django 5.2.5 on 2026-03-11 03:16

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_tecnico', '0025_add_packing_imagen_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventamostrador',
            name='costo_paquete',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo del paquete de servicio (editable)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
