# Generated by Django 5.2.5 on 2026-03-11 03:17

from decimal import Decimal
from django.db import migrations

PRECIOS_PAQUETES_HISTORICOS = {
    'premium': Decimal('5500.00'),
    'oro':     Decimal('3850.00'),
    'plata':   Decimal('2900.00'),
    'ninguno': Decimal('0.00'),
}


def poblar_costo_paquete(apps, schema_editor):
    """
    Asigna costo_paquete a registros históricos usando los precios de referencia.
    Solo actualiza registros que tienen costo_paquete == 0 (recién migrados).
    """
    VentaMostrador = apps.get_model('servicio_tecnico', 'VentaMostrador')
    registros = VentaMostrador.objects.filter(costo_paquete=Decimal('0.00'))
    for venta in registros:
        precio = PRECIOS_PAQUETES_HISTORICOS.get(venta.paquete, Decimal('0.00'))
        venta.costo_paquete = precio
    VentaMostrador.objects.bulk_update(registros, ['costo_paquete'])


def revertir_costo_paquete(apps, schema_editor):
    """Reversión: deja todo en 0 (el campo se elimina en la migración anterior)."""
    VentaMostrador = apps.get_model('servicio_tecnico', 'VentaMostrador')
    VentaMostrador.objects.update(costo_paquete=Decimal('0.00'))


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_tecnico', '0026_add_costo_paquete_field'),
    ]

    operations = [
        migrations.RunPython(poblar_costo_paquete, revertir_costo_paquete),
    ]
