# Generated by Django 5.2.5 on 2026-03-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_tecnico', '0030_feedback_orden_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicio',
            name='es_fuera_garantia',
            field=models.BooleanField(db_index=True, default=False, help_text='¿La orden es fuera de garantía? Se activa automáticamente si orden_cliente tiene prefijo OOW- o FL-'),
        ),
    ]
