# Generated by Django 5.2.5 on 2026-03-13 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_tecnico', '0032_populate_es_fuera_garantia'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnlaceSeguimientoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='Token generado con secrets.token_urlsafe(32). Identifica el enlace de forma única.', max_length=512, unique=True, verbose_name='Token de acceso')),
                ('activo', models.BooleanField(default=True, help_text='Se puede desactivar manualmente desde el admin si es necesario.', verbose_name='Enlace activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación del enlace')),
                ('fecha_ultimo_acceso', models.DateTimeField(blank=True, null=True, verbose_name='Último acceso del cliente')),
                ('accesos_count', models.PositiveIntegerField(default=0, verbose_name='Veces que el cliente abrió el enlace')),
                ('ip_ultimo_acceso', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP del último acceso')),
                ('correo_enviado', models.BooleanField(default=False, help_text='Se actualiza a True cuando la tarea Celery envía el correo.', verbose_name='¿Correo enviado al cliente?')),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enlace_seguimiento', to='servicio_tecnico.ordenservicio', verbose_name='Orden de servicio')),
            ],
            options={
                'verbose_name': 'Enlace de Seguimiento',
                'verbose_name_plural': 'Enlaces de Seguimiento',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
