# Generated by Django 5.2.5 on 2026-03-13 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_agregar_numero_whatsapp_empleado'),
        ('servicio_tecnico', '0033_enlace_seguimiento_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenservicio',
            name='responsable_seguimiento',
            field=models.ForeignKey(blank=True, help_text='Empleado responsable del seguimiento de la orden', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_responsable', to='inventario.empleado'),
        ),
    ]
