# Generated by Django 5.2.5 on 2026-04-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_tecnico', '0035_feedback_recordatorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerPromocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Nombre interno para identificar la promoción. No se muestra al cliente.', max_length=200, verbose_name='Título del banner')),
                ('imagen', models.ImageField(help_text='Sube la imagen en JPG, PNG o WebP. Skyscrapers: 160×600 px recomendado. Header/Footer/Medio: 728×90 px (desktop) o 320×100 px (mobile).', upload_to='banners/%Y/%m/', verbose_name='Imagen del banner')),
                ('url_destino', models.URLField(blank=True, help_text='Link al que va el cliente al hacer clic. Dejar vacío si el banner es solo visual.', verbose_name='URL de destino (opcional)')),
                ('texto_alt', models.CharField(blank=True, help_text="Descripción breve de la imagen para lectores de pantalla. Ejemplo: 'Promoción: 20% off en limpieza de laptop'", max_length=200, verbose_name='Texto alternativo (accesibilidad)')),
                ('posicion', models.CharField(choices=[('skyscraper_izq', 'Skyscraper izquierdo (solo desktop)'), ('skyscraper_der', 'Skyscraper derecho (solo desktop)'), ('header', 'Cabecera — debajo del header del card'), ('medio', 'Medio — entre timeline y contacto'), ('footer', 'Footer — antes del pie de página')], default='footer', help_text='Dónde aparecerá el banner en la página de seguimiento', max_length=20, verbose_name='Posición en la página')),
                ('estado_visible', models.CharField(choices=[('todos', 'Todos los estados (tracking, finalizado y entregado)'), ('tracking', 'Solo en tracking y finalizado'), ('entregado', 'Solo cuando el equipo fue entregado')], default='todos', help_text='Controla en qué etapa del proceso de reparación se muestra el banner', max_length=20, verbose_name='Visible en estado de orden')),
                ('fecha_inicio', models.DateTimeField(help_text='El banner se activa automáticamente a partir de esta fecha', verbose_name='Fecha y hora de inicio')),
                ('fecha_fin', models.DateTimeField(help_text='El banner se desactiva automáticamente después de esta fecha', verbose_name='Fecha y hora de fin')),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar para pausar el banner manualmente sin eliminarlo', verbose_name='Activo')),
                ('orden_display', models.PositiveIntegerField(default=0, help_text='Si hay varios banners en la misma posición, el de menor número aparece primero. Los demás rotan automáticamente.', verbose_name='Orden de aparición')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Banner Promocional',
                'verbose_name_plural': 'Banners Promocionales',
                'ordering': ['orden_display', '-fecha_creacion'],
            },
        ),
    ]
