# Generated by Django 5.2.5 on 2026-04-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_tecnico', '0036_banners_promocionales'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisSentimientoEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentimiento_general', models.CharField(choices=[('positivo', 'Positivo'), ('negativo', 'Negativo'), ('mixto', 'Mixto'), ('neutral', 'Neutral')], default='neutral', max_length=10, verbose_name='Sentimiento General')),
                ('resumen_ejecutivo', models.TextField(help_text='Párrafo de resumen generado por la IA para gerencia.', verbose_name='Resumen Ejecutivo')),
                ('temas_positivos', models.JSONField(default=list, help_text='Lista de aspectos positivos detectados. Ej: ["atención rápida"]', verbose_name='Temas Positivos')),
                ('temas_negativos', models.JSONField(default=list, help_text='Lista de aspectos negativos detectados. Ej: ["tiempo de espera"]', verbose_name='Temas Negativos')),
                ('recomendacion_ia', models.TextField(blank=True, default='', help_text='Acción sugerida por la IA para mejorar la satisfacción.', verbose_name='Recomendación IA')),
                ('total_encuestas', models.PositiveIntegerField(default=0, verbose_name='Total Encuestas Analizadas')),
                ('hash_encuestas', models.CharField(db_index=True, help_text='Fingerprint del set de encuestas. Cambia si llegan nuevas respuestas.', max_length=64, verbose_name='Hash SHA-256 del Conjunto')),
                ('filtros_aplicados', models.JSONField(default=dict, help_text='Filtros activos al momento del análisis (fechas, responsable, sucursal, etc.).', verbose_name='Filtros Aplicados')),
                ('modelo_usado', models.CharField(default='gemma4:e4b', max_length=100, verbose_name='Modelo IA Usado')),
                ('fecha_analisis', models.DateTimeField(auto_now=True, verbose_name='Fecha del Análisis')),
            ],
            options={
                'verbose_name': 'Análisis de Sentimiento (Encuestas)',
                'verbose_name_plural': 'Análisis de Sentimiento (Encuestas)',
                'ordering': ['-fecha_analisis'],
            },
        ),
        migrations.AlterField(
            model_name='bannerpromocional',
            name='imagen',
            field=models.ImageField(help_text='Sube la imagen en JPG, PNG o WebP. Se redimensionará automáticamente al tamaño óptimo según la posición elegida. Skyscrapers: 480×1200 px | Header: 1360×200 px | Medio: 1360×180 px | Footer: 1360×140 px.', upload_to='banners/%Y/%m/', verbose_name='Imagen del banner'),
        ),
    ]
