# Generated by Django 5.2.5 on 2026-05-06 02:36

import django.core.validators
import django.db.models.deletion
import servicio_tecnico.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_agregar_numero_whatsapp_empleado'),
        ('servicio_tecnico', '0037_analisis_sentimiento_encuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialorden',
            name='tipo_evento',
            field=models.CharField(choices=[('creacion', 'Creación de Orden'), ('cambio_estado', 'Cambio de Estado'), ('cambio_tecnico', 'Cambio de Técnico Asignado'), ('comentario', 'Comentario de Usuario'), ('sistema', 'Evento del Sistema'), ('imagen', 'Subida de Imagen'), ('video', 'Subida de Video'), ('cotizacion', 'Evento de Cotización'), ('pieza', 'Evento de Pieza')], help_text='Tipo de evento registrado', max_length=20),
        ),
        migrations.CreateModel(
            name='VideoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso - Estado Inicial'), ('diagnostico', 'Durante Diagnóstico'), ('reparacion', 'Durante Reparación'), ('egreso', 'Egreso - Estado Final'), ('autorizacion', 'Autorización/Pass - RHITSO'), ('packing', 'Packing')], help_text='Tipo de video según la etapa del servicio', max_length=15)),
                ('video', models.FileField(help_text='Archivo de video comprimido (MP4 H.264, máx. 720p)', max_length=255, upload_to=servicio_tecnico.models.video_upload_path, validators=[django.core.validators.FileExtensionValidator(['mp4'])])),
                ('thumbnail', models.ImageField(blank=True, help_text='Miniatura del video para la galería (JPG extraído con FFmpeg)', max_length=255, null=True, upload_to=servicio_tecnico.models.video_thumbnail_upload_path)),
                ('duracion_segundos', models.PositiveIntegerField(blank=True, help_text='Duración del video en segundos (detectada por FFprobe)', null=True)),
                ('tamano_original_mb', models.DecimalField(blank=True, decimal_places=2, help_text='Tamaño del archivo original antes de comprimir (MB)', max_digits=6, null=True)),
                ('tamano_final_mb', models.DecimalField(blank=True, decimal_places=2, help_text='Tamaño del archivo comprimido (MB)', max_digits=6, null=True)),
                ('descripcion', models.CharField(blank=True, help_text='Descripción breve del contenido del video', max_length=200)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se procesó y guardó el video')),
                ('orden', models.ForeignKey(help_text='Orden de servicio a la que pertenece este video', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='servicio_tecnico.ordenservicio')),
                ('subido_por', models.ForeignKey(help_text='Empleado que subió el video', on_delete=django.db.models.deletion.PROTECT, related_name='videos_subidos_servicio', to='inventario.empleado')),
            ],
            options={
                'verbose_name': 'Video de Orden',
                'verbose_name_plural': 'Videos de Órdenes',
                'ordering': ['fecha_subida'],
            },
        ),
    ]
