# Generated by Django 5.2.5 on 2026-05-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_tecnico', '0038_alter_historialorden_tipo_evento_videoorden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoorden',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso - Estado Inicial'), ('diagnostico', 'Durante Diagnóstico'), ('reparacion', 'Durante Reparación'), ('egreso', 'Egreso - Estado Final'), ('autorizacion', 'Autorización/Pass - RHITSO'), ('packing', 'Packing'), ('resumen', 'Video Resumen - Galería'), ('resumen_comprimido', 'Video Resumen Comprimido')], help_text='Tipo de video según la etapa del servicio', max_length=20),
        ),
    ]
