# Generated by Django 5.2.5 on 2026-05-21 04:23

import config.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_tecnico', '0039_videoorden_tipo_max_length_20'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerpromocional',
            name='imagen',
            field=models.ImageField(help_text='Sube la imagen en JPG, PNG, GIF o WebP. Máx 10 MB. Se redimensionará automáticamente al tamaño óptimo según la posición elegida. Skyscrapers: 480×1200 px | Header: 1360×200 px | Medio: 1360×180 px | Footer: 1360×140 px.', upload_to='banners/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp']), config.validators.FileSizeValidator(10)], verbose_name='Imagen del banner'),
        ),
    ]
