# Generated by Django 5.2.5 on 2026-06-17 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_tecnico', '0040_alter_bannerpromocional_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleequipo',
            name='nombre_cliente',
            field=models.CharField(blank=True, help_text='Nombre completo del cliente (opcional, para facturación)', max_length=200),
        ),
        migrations.AddField(
            model_name='detalleequipo',
            name='rfc_cliente',
            field=models.CharField(blank=True, help_text='RFC del cliente (opcional, 13 caracteres para persona física, 12 para moral)', max_length=13),
        ),
        migrations.AddField(
            model_name='detalleequipo',
            name='telefono_cliente',
            field=models.CharField(blank=True, help_text='Teléfono de contacto del cliente (opcional)', max_length=20),
        ),
    ]
