# Generated by Django 5.2.5 on 2026-07-03 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_tecnico', '0042_piezacotizada_precio_unitario_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoSeguimientoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('visita_pagina', 'Visita a la página'), ('pwa_banner_mostrado', 'Banner PWA mostrado'), ('pwa_banner_cerrado', 'Banner PWA cerrado'), ('pwa_prompt_aceptado', 'Prompt PWA aceptado'), ('pwa_prompt_rechazado', 'Prompt PWA rechazado'), ('pwa_instalada', 'PWA instalada'), ('pwa_modo_standalone', 'Página abierta como app instalada'), ('push_activado', 'Push activado'), ('push_desactivado', 'Push desactivado'), ('push_permiso_denegado', 'Permiso push denegado'), ('chat_abierto', 'Chat abierto'), ('chat_mensaje_enviado', 'Mensaje de chat enviado')], db_index=True, max_length=40, verbose_name='Tipo de evento')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha del evento')),
                ('session_id', models.CharField(blank=True, help_text='UUID generado en el navegador para agrupar eventos de una misma visita', max_length=36, verbose_name='ID de sesión')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos extra del evento (sin texto del chat del cliente)', verbose_name='Metadatos')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='User Agent')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('enlace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='servicio_tecnico.enlaceseguimientocliente', verbose_name='Enlace de seguimiento')),
            ],
            options={
                'verbose_name': 'Evento de seguimiento del cliente',
                'verbose_name_plural': 'Eventos de seguimiento del cliente',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['enlace', 'tipo'], name='idx_evt_seg_enlace_tipo'), models.Index(fields=['enlace', 'fecha'], name='idx_evt_seg_enlace_fecha')],
            },
        ),
    ]
