# Generated by Django 5.2.5 on 2026-07-13 23:35
#
# EXPLICACIÓN PARA PRINCIPIANTES:
# 1) Agrega OrdenServicio.costo_mano_obra para guardar la mano de obra
#    sin necesidad de crear una Cotizacion.
# 2) Copia (backfill) el valor desde Cotizacion.costo_mano_obra cuando
#    la orden ya tenía cotización, para no perder lo capturado antes.

from decimal import Decimal

from django.db import migrations, models


def copiar_mano_obra_desde_cotizacion(apps, schema_editor):
    """
    Rellena orden.costo_mano_obra con el valor que ya tenía la Cotizacion.

    Solo actualiza órdenes cuyo campo sigue en 0 y cuya cotización tiene MO > 0,
    para no sobrescribir nada útil en el futuro.
    """
    OrdenServicio = apps.get_model('servicio_tecnico', 'OrdenServicio')
    Cotizacion = apps.get_model('servicio_tecnico', 'Cotizacion')

    # Recorremos cotizaciones con mano de obra registrada
    for cotizacion in Cotizacion.objects.exclude(costo_mano_obra=Decimal('0.00')).iterator():
        # La PK de Cotizacion es la misma que la de OrdenServicio (OneToOne)
        OrdenServicio.objects.filter(
            pk=cotizacion.orden_id,
            costo_mano_obra=Decimal('0.00'),
        ).update(costo_mano_obra=cotizacion.costo_mano_obra)


def revertir_backfill(apps, schema_editor):
    """
    Al revertir la migración no borramos datos de Cotizacion;
    solo dejamos el campo de la orden en 0 (el default).
    """
    OrdenServicio = apps.get_model('servicio_tecnico', 'OrdenServicio')
    OrdenServicio.objects.update(costo_mano_obra=Decimal('0.00'))


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_tecnico', '0048_recordatorio_imagen_egreso_inspector'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicio',
            name='costo_mano_obra',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                help_text=(
                    'Costo de mano de obra del servicio (independiente de si ya hay cotización). '
                    'Al generar la cotización se copia a Cotizacion.costo_mano_obra.'
                ),
                max_digits=10,
            ),
        ),
        migrations.RunPython(
            copiar_mano_obra_desde_cotizacion,
            revertir_backfill,
        ),
    ]
