# Generated by Django 5.2.5 on 2026-07-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Agrega el JSON de sugerencias de piezas del diagnóstico.

    EXPLICACIÓN PARA PRINCIPIANTES:
    Al enviar el diagnóstico ya no se crea Cotizacion/PiezaCotizada en ST.
    Las piezas marcadas se guardan aquí para que Almacén las muestre como ayuda.
    """

    dependencies = [
        ('servicio_tecnico', '0049_ordenservicio_costo_mano_obra'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleequipo',
            name='piezas_sugeridas_diagnostico',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text=(
                    'Sugerencias de piezas detectadas/marcadas al enviar el diagnóstico. '
                    'No crea cotización en ST; Almacén las muestra como ayuda al cotizar.'
                ),
            ),
        ),
    ]
