# Generated by Django 5.2.5 on 2026-07-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_tecnico', '0051_formato_servicio_oow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenorden',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso - Estado Inicial'), ('diagnostico', 'Durante Diagnóstico'), ('reparacion', 'Durante Reparación'), ('egreso', 'Egreso - Estado Final'), ('autorizacion', 'Autorización/Pass - RHITSO'), ('packing', 'Imágenes Packing'), ('identificacion_oow', 'Identificación oficial — Formato OOW'), ('escaneo_oow', 'Resultado de escaneo — Formato OOW')], help_text='Tipo de imagen (ingreso, egreso, diagnóstico, evidencia OOW, etc.)', max_length=40),
        ),
    ]
