# Generated by Django 5.2.5 on 2026-07-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_tecnico', '0052_imagen_identificacion_oow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formatoserviciooow',
            name='tipo_diagrama',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('escritorio', 'Escritorio'), ('aio', 'All in One')], default='laptop', help_text='Tipo de esquema para marcar daños estéticos', max_length=20),
        ),
    ]
