# Generated by Django 5.2.5 on 2026-07-20 19:58

from django.db import migrations, models


def copiar_email_envio_a_lista(apps, schema_editor):
    """
    EXPLICACIÓN PARA PRINCIPIANTES:
    Formatos ya guardados solo tenían email_envio (un correo).
    Aquí lo copiamos a emails_envio como lista de 1 elemento.
    """
    FormatoServicioOOW = apps.get_model('servicio_tecnico', 'FormatoServicioOOW')
    for formato in FormatoServicioOOW.objects.all().iterator():
        emails = formato.emails_envio or []
        if emails:
            continue
        if formato.email_envio:
            formato.emails_envio = [formato.email_envio]
            formato.save(update_fields=['emails_envio'])


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_tecnico', '0053_formato_oow_tipo_aio'),
    ]

    operations = [
        migrations.AddField(
            model_name='formatoserviciooow',
            name='emails_envio',
            field=models.JSONField(blank=True, default=list, help_text='Lista de hasta 3 correos para enviar el PDF del formato'),
        ),
        migrations.AlterField(
            model_name='formatoserviciooow',
            name='email_envio',
            field=models.EmailField(blank=True, help_text='Correo principal al que se enviará el PDF (compatibilidad; ver emails_envio)', max_length=254),
        ),
        migrations.RunPython(copiar_email_envio_a_lista, migrations.RunPython.noop),
    ]
