# Generated by Django 5.2.5 on 2026-07-20 23:39

import django.core.validators
import django.db.models.deletion
import servicio_tecnico.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_sucursal_horario_atencion'),
        ('servicio_tecnico', '0054_formato_oow_emails_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenorden',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso - Estado Inicial'), ('diagnostico', 'Durante Diagnóstico'), ('reparacion', 'Durante Reparación'), ('egreso', 'Egreso - Estado Final'), ('autorizacion', 'Autorización/Pass - RHITSO'), ('packing', 'Imágenes Packing'), ('identificacion_oow', 'Identificación oficial — Formato OOW'), ('escaneo_oow', 'Resultado de escaneo — Formato OOW'), ('escaneo_garantia', 'Resultado de escaneo — Formato Garantía Dell')], help_text='Tipo de imagen (ingreso, egreso, diagnóstico, evidencia OOW, etc.)', max_length=40),
        ),
        migrations.CreateModel(
            name='FormatoServicioGarantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('finalizado', 'Finalizado')], default='borrador', help_text='Borrador editable o finalizado (PDF generado)', max_length=20)),
                ('tipo_diagrama', models.CharField(choices=[('laptop', 'Laptop'), ('escritorio', 'Escritorio'), ('aio', 'All in One')], default='laptop', help_text='Tipo de esquema para marcar daños estéticos', max_length=20)),
                ('accesorio_cargador', models.BooleanField(default=False)),
                ('accesorio_teclado', models.BooleanField(default=False)),
                ('accesorio_pluma', models.BooleanField(default=False)),
                ('accesorio_mouse', models.BooleanField(default=False)),
                ('accesorio_monitor', models.BooleanField(default=False)),
                ('accesorio_caja', models.BooleanField(default=False)),
                ('accesorio_bateria', models.BooleanField(default=False)),
                ('accesorio_docking', models.BooleanField(default=False)),
                ('accesorio_microsd_sim', models.BooleanField(default=False)),
                ('accesorio_otros', models.BooleanField(default=False)),
                ('accesorios_otros_detalle', models.CharField(blank=True, help_text='Detalle cuando se marca “Otros”', max_length=200)),
                ('numero_cargador', models.CharField(blank=True, help_text='Número de serie / descripción del cargador', max_length=100)),
                ('observaciones_tecnicas', models.TextField(blank=True, help_text='Observaciones técnicas y detalle de daños estéticos')),
                ('disclaimer_pc_audit', models.BooleanField(default=False, help_text='PC AUDIT no pudo usarse (equipo no enciende / sin Windows / falla impide herramienta)')),
                ('acepta_condiciones', models.BooleanField(default=False, help_text='Cliente acepta las condiciones en que entrega el equipo')),
                ('acepta_privacidad', models.BooleanField(default=False, help_text='Cliente aceptó el aviso de privacidad vigente')),
                ('version_aviso_privacidad', models.CharField(blank=True, default='', help_text='Versión del aviso aceptado (ej. mx-2016-09-06)', max_length=40)),
                ('email_envio', models.EmailField(blank=True, help_text='Correo principal al que se enviará el PDF (compatibilidad; ver emails_envio)', max_length=254)),
                ('emails_envio', models.JSONField(blank=True, default=list, help_text='Lista de hasta 3 correos para enviar el PDF del formato')),
                ('como_enteraste', models.CharField(blank=True, choices=[('google', 'Google'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('referencia', 'Referencia personal'), ('dell', 'DELL'), ('ventas', 'Ventas')], help_text='¿Cómo se enteró el cliente de SIC?', max_length=30)),
                ('nombre_tecnico', models.CharField(blank=True, help_text='Nombre del técnico que diagnostica y repara', max_length=150)),
                ('firma_cliente', models.ImageField(blank=True, help_text='Firma digital del cliente (PNG del canvas)', max_length=255, null=True, upload_to=servicio_tecnico.models.formato_garantia_firma_upload_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
                ('firma_tecnico', models.ImageField(blank=True, help_text='Firma digital del técnico (opcional)', max_length=255, null=True, upload_to=servicio_tecnico.models.formato_garantia_firma_upload_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
                ('pdf', models.FileField(blank=True, help_text='PDF generado al finalizar el formato', max_length=255, null=True, upload_to=servicio_tecnico.models.formato_garantia_pdf_upload_path)),
                ('finalizado_en', models.DateTimeField(blank=True, help_text='Fecha/hora en que se finalizó el formato', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, help_text='Último empleado que guardó el formato', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formatos_garantia_actualizados', to='inventario.empleado')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Empleado que inició el formato', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formatos_garantia_creados', to='inventario.empleado')),
                ('orden', models.OneToOneField(help_text='Orden de servicio a la que pertenece este formato', on_delete=django.db.models.deletion.CASCADE, related_name='formato_garantia', to='servicio_tecnico.ordenservicio')),
            ],
            options={
                'verbose_name': 'Formato de Servicio Garantía Dell',
                'verbose_name_plural': 'Formatos de Servicio Garantía Dell',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='DanoEsteticoVistaGarantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_vista', models.CharField(help_text='Clave de la vista (pantalla, top_cover, palm, …)', max_length=40)),
                ('etiqueta_dano', models.CharField(blank=True, help_text='Etiqueta del tipo de daño (ej. Rayado)', max_length=80)),
                ('imagen_anotada', models.ImageField(blank=True, help_text='Imagen del diagrama con anotaciones del técnico', max_length=255, null=True, upload_to=servicio_tecnico.models.dano_estetico_garantia_upload_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('formato', models.ForeignKey(help_text='Formato Garantía al que pertenece esta vista', on_delete=django.db.models.deletion.CASCADE, related_name='vistas_dano', to='servicio_tecnico.formatoserviciogarantia')),
            ],
            options={
                'verbose_name': 'Vista de daño estético Garantía',
                'verbose_name_plural': 'Vistas de daño estético Garantía',
                'ordering': ['clave_vista'],
                'unique_together': {('formato', 'clave_vista')},
            },
        ),
    ]
