# Generated by Django 5.2.5 on 2026-07-21 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_tecnico', '0055_formato_servicio_garantia'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleequipo',
            name='direccion_cliente',
            field=models.CharField(blank=True, help_text='Dirección del cliente (calle, colonia, C.P.; opcional)', max_length=300),
        ),
    ]
