# Generated by Django 5.2.5 on 2026-07-21 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_sucursal_horario_atencion'),
        ('servicio_tecnico', '0056_detalleequipo_direccion_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicio',
            name='aviso_recepcion_listo_enviado',
            field=models.BooleanField(default=False, help_text='¿Ya se avisó a recepción (campanita/push) de que el equipo está listo para notificar recolección al cliente?'),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='fecha_notificacion_equipo_disponible',
            field=models.DateTimeField(blank=True, help_text="Fecha en que se envió al cliente el correo de 'equipo disponible para recolección'", null=True),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='usuario_notificacion_equipo_disponible',
            field=models.ForeignKey(blank=True, help_text='Empleado que envió el correo de equipo disponible al cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_notificacion_equipo_disponible', to='inventario.empleado'),
        ),
    ]
