# Generated by Django 5.2.14 on 2026-07-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_tecnico', '0058_detalleequipo_fecha_importacion_sicser'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisissentimientoencuesta',
            name='tipo_encuesta',
            field=models.CharField(choices=[('satisfaccion', 'Satisfacción'), ('rechazo', 'Rechazo de cotización')], db_index=True, default='satisfaccion', help_text='Separá la caché de satisfacción de la de rechazo.', max_length=20, verbose_name='Tipo de encuesta'),
        ),
        migrations.AlterField(
            model_name='analisissentimientoencuesta',
            name='recomendacion_ia',
            field=models.TextField(blank=True, default='', help_text='Acción sugerida por la IA (satisfacción o conversión).', verbose_name='Recomendación IA'),
        ),
    ]
