# Generated by Django 5.2.14 on 2026-08-05 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_tecnico', '0060_seguimiento_pieza_orden_y_piezas_vm'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='seguimientopieza',
            new_name='servicio_te_orden_i_4d21f3_idx',
            old_name='servicio_te_orden_i_7e2a1b_idx',
        ),
        migrations.RenameIndex(
            model_name='seguimientopieza',
            new_name='servicio_te_fecha_p_6bd9ce_idx',
            old_name='servicio_te_fecha_p_9c4d2e_idx',
        ),
    ]
