# Generated by Django 5.2.14 on 2026-08-14 22:41

import config.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import servicio_tecnico.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0020_empleado_rol_facturacion'),
        ('servicio_tecnico', '0062_piezaventamostrador_solicitud_baja'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto cobrado en este abono (debe ser mayor a cero)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('tipo', models.CharField(choices=[('anticipo', 'Anticipo (50% para iniciar)'), ('saldo', 'Saldo (resto a la entrega)'), ('pago_completo', 'Pago en una sola exhibición'), ('otro', 'Otro abono')], default='anticipo', help_text='Si es el anticipo del 50%, el saldo, un pago único u otro', max_length=20)),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('otro', 'Otro')], default='transferencia', help_text='Cómo pagó el cliente', max_length=20)),
                ('comprobante', models.ImageField(blank=True, help_text='Foto o captura del comprobante (opcional, máx. 10 MB)', max_length=255, null=True, upload_to=servicio_tecnico.models.comprobante_pago_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp']), config.validators.FileSizeValidator(10)])),
                ('notas', models.CharField(blank=True, help_text='Referencia de transferencia, últimos 4 dígitos, etc.', max_length=250)),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se recibió el pago')),
                ('orden', models.ForeignKey(help_text='Orden de servicio a la que se aplica este pago', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='servicio_tecnico.ordenservicio')),
                ('registrado_por', models.ForeignKey(help_text='Empleado que capturó este pago en el sistema', on_delete=django.db.models.deletion.PROTECT, related_name='pagos_registrados', to='inventario.empleado')),
            ],
            options={
                'verbose_name': 'Pago de orden',
                'verbose_name_plural': 'Pagos de órdenes',
                'ordering': ['fecha_pago'],
                'indexes': [models.Index(fields=['orden', 'fecha_pago'], name='servicio_te_orden_i_f15497_idx')],
            },
        ),
    ]
