# Generated by Django 5.2.14 on 2026-08-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Documenta que `recomienda` ya no se pregunta al cliente: se deriva
    del NPS al guardar (0–6 = no, 7–10 = sí). Solo cambia help_text y
    verbose_name; no toca datos ni el tipo de columna.
    """

    dependencies = [
        ('servicio_tecnico', '0063_pago_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackcliente',
            name='recomienda',
            field=models.BooleanField(blank=True, help_text='Se calcula al guardar a partir del NPS (0–6 = no, 7–10 = sí). Ya no se pregunta al cliente en el formulario.', null=True, verbose_name='¿Recomendaría el servicio?'),
        ),
    ]
