# Generated by Django 5.2.14 on 2026-08-17 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Facturación confirma si un pago (transferencia/tarjeta) ya aparece
    en la cuenta de la empresa. Campos de estado + auditoría en PagoOrden.
    Los pagos viejos quedan en no_aplica (no se reabren).
    """

    dependencies = [
        ('inventario', '0020_empleado_rol_facturacion'),
        ('servicio_tecnico', '0064_feedback_recomienda_derivado_nps'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoorden',
            name='estado_validacion',
            field=models.CharField(
                choices=[
                    ('no_aplica', 'No requiere validación'),
                    ('pendiente', 'Pendiente de validar en cuenta'),
                    ('validado', 'Validado en cuenta'),
                    ('no_aparece', 'No aparece en cuenta'),
                ],
                db_index=True,
                default='no_aplica',
                help_text=(
                    'Si Facturación ya confirmó que este abono aparece '
                    'en la cuenta de la empresa'
                ),
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='pagoorden',
            name='fecha_validacion',
            field=models.DateTimeField(
                blank=True,
                help_text='Momento en que se marcó validado o no_aparece',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='pagoorden',
            name='nota_validacion',
            field=models.CharField(
                blank=True,
                help_text='Comentario de Facturación (útil si el pago no aparece)',
                max_length=250,
            ),
        ),
        migrations.AddField(
            model_name='pagoorden',
            name='validado_por',
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    'Empleado de Facturación (o gerencia) que confirmó el abono'
                ),
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='pagos_validados',
                to='inventario.empleado',
            ),
        ),
    ]
