# Generated by Django 5.2.14 on 2026-08-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    El formato OOW ahora guarda el número de serie del cargador
    (igual que el formato Dell) para copiarlo a DetalleEquipo al guardar.
    """

    dependencies = [
        ('servicio_tecnico', '0065_pago_orden_validacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='formatoserviciooow',
            name='numero_cargador',
            field=models.CharField(
                blank=True,
                help_text='Número de serie / descripción del cargador',
                max_length=100,
            ),
        ),
    ]
