# Generated by Django 5.2.14 on 2026-08-25 18:06

import django.db.models.deletion
import servicio_tecnico.models_facturacion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_tecnico', '0066_formato_oow_numero_cargador'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteFiscalOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_id', models.PositiveBigIntegerField(db_index=True, help_text='Número público del API (dígitos de orden_cliente)')),
                ('solicitado_en', models.DateTimeField(blank=True, help_text='Momento del GET previo. Sin esto el PUT responde 404.', null=True)),
                ('uuid', models.CharField(blank=True, db_index=True, help_text='UUID fiscal del SAT (vacío hasta el PUT)', max_length=36)),
                ('fecha_timbrado', models.DateTimeField(blank=True, help_text='fechaTimbrado del payload VO', null=True)),
                ('cadena_original_sat', models.TextField(blank=True)),
                ('no_certificado_sat', models.CharField(blank=True, max_length=40)),
                ('no_certificado_cfdi', models.CharField(blank=True, max_length=40)),
                ('sello_sat', models.TextField(blank=True)),
                ('sello_cfdi', models.TextField(blank=True)),
                ('qr_code', models.TextField(blank=True, help_text='QR del timbrado (texto o base64, como lo manda VO)')),
                ('cfdi_xml', models.FileField(blank=True, help_text='XML del CFDI (campo cfdi del PUT)', max_length=255, upload_to=servicio_tecnico.models_facturacion.cfdi_xml_upload_path)),
                ('pdf', models.FileField(blank=True, help_text='PDF de la factura (campo pdf64 del PUT, base64)', max_length=255, upload_to=servicio_tecnico.models_facturacion.cfdi_pdf_upload_path)),
                ('recibido_en', models.DateTimeField(blank=True, help_text='Cuándo SIGMA aceptó el PUT timbrado', null=True)),
                ('orden', models.OneToOneField(help_text='Orden cuya venta se facturó o se está facturando', on_delete=django.db.models.deletion.CASCADE, related_name='comprobante_fiscal', to='servicio_tecnico.ordenservicio')),
            ],
            options={
                'verbose_name': 'Comprobante fiscal de orden',
                'verbose_name_plural': 'Comprobantes fiscales de órdenes',
                'constraints': [models.UniqueConstraint(condition=models.Q(('uuid__gt', '')), fields=('uuid',), name='unico_cfdi_uuid_sat')],
            },
        ),
    ]
