# Generated by Django 5.2.14 on 2026-08-26 19:29

import django.core.validators
import django.db.models.deletion
import servicio_tecnico.models_formato_venta_mostrador
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0020_empleado_rol_facturacion'),
        ('servicio_tecnico', '0067_comprobante_fiscal_orden'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatoServicioVentaMostrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('finalizado', 'Finalizado')], default='borrador', help_text='Borrador editable o finalizado (PDF generado)', max_length=20)),
                ('tipo_diagrama', models.CharField(choices=[('laptop', 'Laptop'), ('escritorio', 'Escritorio'), ('aio', 'All in One')], default='laptop', help_text='Tipo de esquema para marcar daños estéticos (opcional)', max_length=20)),
                ('empresa_cliente', models.CharField(blank=True, help_text='Razón social / empresa (si difiere del nombre del cliente)', max_length=200)),
                ('persona_contacto', models.CharField(blank=True, help_text='Persona de contacto (opcional; si vacío se usa nombre_cliente)', max_length=200)),
                ('numero_cargador', models.CharField(blank=True, help_text='Número de serie / descripción del cargador (opcional)', max_length=100)),
                ('email_envio', models.EmailField(blank=True, help_text='Correo principal (compatibilidad; ver emails_envio)', max_length=254)),
                ('emails_envio', models.JSONField(blank=True, default=list, help_text='Lista de hasta 3 correos para enviar el PDF')),
                ('firma_entrega_cis', models.ImageField(blank=True, help_text='Firma de entrega de equipo en CIS (opcional)', max_length=255, null=True, upload_to=servicio_tecnico.models_formato_venta_mostrador.formato_vm_firma_upload_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
                ('firma_entrega_cliente', models.ImageField(blank=True, help_text='Firma de entrega de equipo a cliente (opcional)', max_length=255, null=True, upload_to=servicio_tecnico.models_formato_venta_mostrador.formato_vm_firma_upload_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
                ('pdf', models.FileField(blank=True, help_text='PDF generado al finalizar el formato', max_length=255, null=True, upload_to=servicio_tecnico.models_formato_venta_mostrador.formato_vm_pdf_upload_path)),
                ('finalizado_en', models.DateTimeField(blank=True, help_text='Fecha/hora en que se finalizó el formato', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, help_text='Último empleado que guardó el formato', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formatos_venta_mostrador_actualizados', to='inventario.empleado')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Empleado que inició el formato', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formatos_venta_mostrador_creados', to='inventario.empleado')),
                ('orden', models.OneToOneField(help_text='Orden de venta mostrador a la que pertenece este formato', on_delete=django.db.models.deletion.CASCADE, related_name='formato_venta_mostrador', to='servicio_tecnico.ordenservicio')),
            ],
            options={
                'verbose_name': 'Formato de Venta Mostrador',
                'verbose_name_plural': 'Formatos de Venta Mostrador',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='DanoEsteticoVistaVentaMostrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_vista', models.CharField(help_text='Clave de la vista (pantalla, top_cover, palm, …)', max_length=40)),
                ('etiqueta_dano', models.CharField(blank=True, help_text='Etiqueta del tipo de daño (ej. Rayado)', max_length=80)),
                ('imagen_anotada', models.ImageField(blank=True, help_text='Imagen del diagrama con anotaciones (opcional)', max_length=255, null=True, upload_to=servicio_tecnico.models_formato_venta_mostrador.dano_estetico_vm_upload_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('formato', models.ForeignKey(help_text='Formato de venta mostrador al que pertenece esta vista', on_delete=django.db.models.deletion.CASCADE, related_name='vistas_dano', to='servicio_tecnico.formatoservicioventamostrador')),
            ],
            options={
                'verbose_name': 'Vista de daño estético VM',
                'verbose_name_plural': 'Vistas de daño estético VM',
                'ordering': ['clave_vista'],
                'unique_together': {('formato', 'clave_vista')},
            },
        ),
    ]
