# Generated by Django 5.2.14 on 2026-09-17

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    El formato OOW guarda número de serie de maletín, mouse, teclado
    y monitor (igual que el cargador). Al finalizar, si el accesorio
    está marcado, esa serie es obligatoria.
    """

    dependencies = [
        ('servicio_tecnico', '0069_detalleequipo_razon_social_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='formatoserviciooow',
            name='numero_maletin',
            field=models.CharField(
                blank=True,
                help_text='Número de serie del maletín (si se entregó)',
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name='formatoserviciooow',
            name='numero_mouse',
            field=models.CharField(
                blank=True,
                help_text='Número de serie del mouse (si se entregó)',
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name='formatoserviciooow',
            name='numero_teclado',
            field=models.CharField(
                blank=True,
                help_text='Número de serie del teclado (si se entregó)',
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name='formatoserviciooow',
            name='numero_monitor',
            field=models.CharField(
                blank=True,
                help_text='Número de serie del monitor (si se entregó)',
                max_length=100,
            ),
        ),
    ]
