# Generated by Django 5.2.14 on 2026-09-17 19:18

import config.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Tabla hermana de BannerPromocional: flyers para la hoja extra del PDF OOW.

    No comparte posiciones web ni recorte a slots; marketing vigila fechas
    y el generador PDF pega lo vigente después del aviso de privacidad.
    """

    dependencies = [
        ('servicio_tecnico', '0070_formato_oow_numeros_accesorios'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaniaPdfOow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Nombre para identificar la campaña en el admin. No se imprime.', max_length=200, verbose_name='Título interno')),
                ('imagen', models.ImageField(help_text='Flyer o ficha de producto (JPG, PNG, GIF o WebP). Máx. 10 MB. Se escala si pasa de 1800 px de lado, sin recortar. Retrato (laptop) o apaisado: el PDF ajusta el marco al ratio.', upload_to='campanias_pdf_oow/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp']), config.validators.FileSizeValidator(10)], verbose_name='Imagen de la campaña')),
                ('url_destino', models.URLField(blank=True, help_text='Si hay enlace, en el PDF digital el cliente puede tocar la imagen para abrir la promoción. No se imprime la URL ni un QR extra.', max_length=500, verbose_name='URL de destino (opcional)')),
                ('texto_alt', models.CharField(blank=True, help_text='Descripción corta de la imagen (accesibilidad / pie de foto).', max_length=200, verbose_name='Texto alternativo')),
                ('leyenda', models.CharField(blank=True, help_text='Frase visible debajo de la imagen. Si se deja vacía, se usa el texto alternativo.', max_length=240, verbose_name='Leyenda en el PDF')),
                ('fecha_inicio', models.DateTimeField(help_text='La campaña entra al PDF a partir de esta fecha.', verbose_name='Fecha y hora de inicio')),
                ('fecha_fin', models.DateTimeField(help_text='Después de esta fecha ya no se adjunta al PDF.', verbose_name='Fecha y hora de fin')),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar para pausar sin borrar la campaña.', verbose_name='Activo')),
                ('orden_display', models.PositiveIntegerField(default=0, help_text='Número menor = se imprime primero. Si no caben, siguen en la hoja siguiente.', verbose_name='Orden de aparición')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Campaña PDF OOW',
                'verbose_name_plural': 'Campañas PDF OOW',
                'ordering': ['orden_display', '-fecha_creacion'],
            },
        ),
    ]
