# Generated by Django 5.2.14 on 2026-09-19 03:11

import django.db.models.deletion
import servicio_tecnico.models_facturacion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_tecnico', '0071_campania_pdf_oow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagoorden',
            name='tipo',
            field=models.CharField(choices=[('anticipo', 'Anticipo (50% para iniciar)'), ('saldo', 'Saldo (resto a la entrega)'), ('pago_completo', 'Pago en una sola exhibición'), ('diagnostico', 'Diagnóstico / mano de obra'), ('otro', 'Otro abono')], default='anticipo', help_text='Si es el anticipo del 50%, el saldo, un pago único u otro', max_length=20),
        ),
        migrations.CreateModel(
            name='DocumentoFiscalOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_id', models.CharField(db_index=True, help_text='Identificador público del portal (ej. SAT9596-1)', max_length=32, unique=True)),
                ('tipo', models.CharField(choices=[('pue', 'PUE — Pago en una sola exhibición'), ('ppd', 'PPD — Pago en parcialidades o diferido')], help_text='PUE (servicio pagado al 100%) o PPD (anticipo)', max_length=3)),
                ('descripcion', models.CharField(help_text='Texto del concepto: Diagnóstico, Limpieza y Mantenimiento, Anticipo…', max_length=200)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Importe antes de IVA', max_digits=12)),
                ('tasa_iva', models.DecimalField(decimal_places=4, default=Decimal('0.1600'), help_text='Tasa de IVA aplicada (0.1600 = 16%)', max_digits=6)),
                ('iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Importe del IVA trasladado', max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Subtotal + IVA (lo que se factura)', max_digits=12)),
                ('moneda', models.CharField(default='MXN', help_text='Moneda del comprobante (hoy siempre MXN)', max_length=3)),
                ('disponible_desde', models.DateTimeField(blank=True, help_text='Cuándo se validó el pago y el cliente pudo ver el webId', null=True)),
                ('solicitado_en', models.DateTimeField(blank=True, help_text='Momento del GET del portal. Sin esto el PUT responde 404.', null=True)),
                ('uuid', models.CharField(blank=True, db_index=True, help_text='UUID fiscal del SAT (vacío hasta el PUT)', max_length=36)),
                ('fecha_timbrado', models.DateTimeField(blank=True, help_text='fechaTimbrado del payload VO', null=True)),
                ('cadena_original_sat', models.TextField(blank=True)),
                ('no_certificado_sat', models.CharField(blank=True, max_length=40)),
                ('no_certificado_cfdi', models.CharField(blank=True, max_length=40)),
                ('sello_sat', models.TextField(blank=True)),
                ('sello_cfdi', models.TextField(blank=True)),
                ('qr_code', models.TextField(blank=True, help_text='QR del timbrado (texto o base64, como lo manda VO)')),
                ('cfdi_xml', models.FileField(blank=True, help_text='XML del CFDI (campo cfdi del PUT)', max_length=255, upload_to=servicio_tecnico.models_facturacion.cfdi_xml_upload_path)),
                ('pdf', models.FileField(blank=True, help_text='PDF de la factura (campo pdf64 del PUT, base64)', max_length=255, upload_to=servicio_tecnico.models_facturacion.cfdi_pdf_upload_path)),
                ('recibido_en', models.DateTimeField(blank=True, help_text='Cuándo SIGMA aceptó el PUT timbrado', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('orden', models.ForeignKey(help_text='Orden cuya venta se factura', on_delete=django.db.models.deletion.CASCADE, related_name='documentos_fiscales', to='servicio_tecnico.ordenservicio')),
            ],
            options={
                'verbose_name': 'Documento fiscal de orden',
                'verbose_name_plural': 'Documentos fiscales de órdenes',
                'ordering': ['orden_id', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='ConceptoDocumentoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Texto del concepto tal como aparece en la factura', max_length=200)),
                ('clave_sat', models.CharField(help_text='ClaveProdServ del SAT (ej. 81111812 servicios técnicos)', max_length=12)),
                ('clave_unidad', models.CharField(help_text='ClaveUnidad del SAT (ej. E48 unidad de servicio)', max_length=6)),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio antes de IVA', max_digits=12)),
                ('importe', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='cantidad × precio_unitario (antes de IVA)', max_digits=12)),
                ('orden_linea', models.PositiveSmallIntegerField(default=1, help_text='Posición de la línea dentro del documento')),
                ('documento', models.ForeignKey(help_text='Documento fiscal al que pertenece la línea', on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='servicio_tecnico.documentofiscalorden')),
            ],
            options={
                'verbose_name': 'Concepto de documento fiscal',
                'verbose_name_plural': 'Conceptos de documentos fiscales',
                'ordering': ['documento_id', 'orden_linea', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='ComprobanteFiscalOrden',
        ),
        migrations.AddConstraint(
            model_name='documentofiscalorden',
            constraint=models.UniqueConstraint(fields=('orden', 'tipo'), name='unico_documento_fiscal_por_tipo'),
        ),
        migrations.AddConstraint(
            model_name='documentofiscalorden',
            constraint=models.UniqueConstraint(condition=models.Q(('uuid__gt', '')), fields=('uuid',), name='unico_cfdi_uuid_sat'),
        ),
    ]
