# Generated by Django 5.2.14 on 2026-09-19 03:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_tecnico', '0072_documentos_fiscales_pue_ppd'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicio',
            name='perfil_diagnostico',
            field=models.CharField(blank=True, choices=[('mostrador', 'Mostrador (sin cargo de diagnóstico)'), ('estandar', 'Estándar'), ('express', 'Express'), ('alta_gama', 'Alta Gama'), ('server', 'Server'), ('rep_nivel_componente', 'Reparación nivel componente (sin cargo)')], default='', help_text='Tipo de diagnóstico cobrado. Define el monto de mano de obra (sin IVA) según el tarifario del cotizador. Vacío = orden con monto capturado a mano.', max_length=30, verbose_name='Tipo de diagnóstico'),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='costo_mano_obra',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo de mano de obra del servicio, SIN IVA (independiente de si ya hay cotización). Lo calcula SIGMA a partir de perfil_diagnostico; no se teclea. Al generar la cotización se copia a Cotizacion.costo_mano_obra.', max_digits=10),
        ),
    ]
