# Generated by Django 5.2.14 on 2026-09-21 18:08

from django.db import migrations, models


def reclasificar_pagos_existentes(apps, schema_editor):
    """
    Pasa los abonos viejos al esquema saldo + tipo.

    El diagnóstico era un tipo de pago; ahora es el saldo que se cubre y
    siempre cuenta como una sola exhibición. "Saldo" y "Otro" eran
    parcialidades de la reparación, así que quedan como anticipo.

    Args:
        apps: registro histórico de modelos de la migración.
        schema_editor: conexión de esta base (un país por corrida).

    Efectos secundarios:
        UPDATE sobre PagoOrden en el alias de schema_editor.
    """
    PagoOrden = apps.get_model('servicio_tecnico', 'PagoOrden')
    db_alias = schema_editor.connection.alias
    # Paso 1: el diagnóstico deja de ser un tipo y pasa al bolsillo propio.
    PagoOrden.objects.using(db_alias).filter(tipo='diagnostico').update(
        saldo_a_cubrir='diagnostico',
        tipo='pago_completo',
    )
    # Paso 2: las parcialidades viejas (saldo / otro) son anticipo de reparación.
    PagoOrden.objects.using(db_alias).filter(tipo__in=('saldo', 'otro')).update(
        tipo='anticipo',
        saldo_a_cubrir='reparacion',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_tecnico', '0073_ordenservicio_perfil_diagnostico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoorden',
            name='saldo_a_cubrir',
            field=models.CharField(choices=[('diagnostico', 'Diagnóstico'), ('reparacion', 'Reparación / servicios aceptados')], default='reparacion', help_text='Si este abono cubre el diagnóstico o la reparación / servicios', max_length=20),
        ),
        migrations.RunPython(
            reclasificar_pagos_existentes,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='documentofiscalorden',
            name='tipo',
            field=models.CharField(choices=[('pue', 'PUE — Diagnóstico'), ('pue_rep', 'PUE — Pago en una sola exhibición'), ('ppd', 'PPD — Anticipo')], help_text='pue (diagnóstico), pue_rep (contado de la reparación) o ppd', max_length=16),
        ),
        migrations.AlterField(
            model_name='pagoorden',
            name='estado_validacion',
            field=models.CharField(choices=[('no_aplica', 'No requiere validación'), ('pendiente', 'Pendiente de validar en cuenta'), ('validado', 'Validado en cuenta'), ('no_aparece', 'No aparece en cuenta')], db_index=True, default='pendiente', help_text='Si Facturación ya confirmó que este abono aparece en la cuenta de la empresa', max_length=20),
        ),
        migrations.AlterField(
            model_name='pagoorden',
            name='metodo',
            field=models.CharField(choices=[('transferencia', 'Transferencia'), ('tarjeta_credito', 'Tarjeta de crédito'), ('tarjeta_debito', 'Tarjeta de débito'), ('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('otro', 'Otro')], default='transferencia', help_text='Transferencia, tarjeta de crédito o tarjeta de débito', max_length=20),
        ),
        migrations.AlterField(
            model_name='pagoorden',
            name='tipo',
            field=models.CharField(choices=[('anticipo', 'Anticipo'), ('pago_completo', 'Pago en una sola exhibición')], default='anticipo', help_text='Anticipo (factura PPD) o pago en una sola exhibición (factura PUE)', max_length=20),
        ),
    ]
