# Generated by Django 5.2.14 on 2026-09-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_tecnico', '0074_pagos_saldo_a_cubrir_y_pue_reparacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptodocumentofiscal',
            name='clave_sat',
            field=models.CharField(help_text='ClaveProdServ del SAT (8 dígitos; la de cada servicio está en facturacion_documentos)', max_length=12),
        ),
    ]
