# Generated by Django 5.2.14 on 2026-09-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_tecnico', '0075_clave_sat_help_text_catalogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentofiscalorden',
            name='descripcion',
            field=models.CharField(help_text='Etiqueta del seguimiento: Diagnóstico, Reparación o Anticipo Reparación', max_length=200),
        ),
    ]
