# Generated by Django 5.2.14 on 2026-10-08 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0023_empleado_atiende_garantias_marca'),
        ('servicio_tecnico', '0076_etiqueta_seguimiento_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenservicio',
            name='tecnico_asignado_actual',
            field=models.ForeignKey(blank=True, help_text='Técnico actualmente asignado a la orden. Vacío = sin asignar (se elige después).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_tecnico', to='inventario.empleado'),
        ),
    ]
