# Generated by Django 5.2.8 on 2025-12-03 03:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0013_empleado_foto_perfil'),
        ('servicio_tecnico', '0018_alter_cotizacion_motivo_rechazo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre único para la categoría (ej: Repuestos, Consumibles)', max_length=100, unique=True, verbose_name='Nombre de Categoría')),
                ('descripcion', models.TextField(blank=True, help_text='Explicación de qué productos incluye esta categoría', verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar para ocultar la categoría sin eliminarla', verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Categoría de Almacén',
                'verbose_name_plural': 'Categorías de Almacén',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo o razón social del proveedor', max_length=200, unique=True, verbose_name='Nombre del Proveedor')),
                ('contacto', models.CharField(blank=True, help_text='Nombre de la persona con quien tratar', max_length=100, verbose_name='Persona de Contacto')),
                ('telefono', models.CharField(blank=True, help_text='Número de teléfono principal', max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, help_text='Email para pedidos y comunicación', max_length=254, verbose_name='Correo Electrónico')),
                ('direccion', models.TextField(blank=True, help_text='Dirección física del proveedor', verbose_name='Dirección')),
                ('tiempo_entrega_dias', models.IntegerField(default=7, help_text='Tiempo promedio de entrega en días hábiles', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tiempo de Entrega (días)')),
                ('notas', models.TextField(blank=True, help_text='Observaciones: descuentos, condiciones de pago, etc.', verbose_name='Notas')),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar si ya no se trabaja con este proveedor', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('completa', 'Auditoría Completa'), ('ciclica', 'Auditoría Cíclica'), ('diferencias', 'Auditoría por Diferencias'), ('abc', 'Auditoría ABC (Alto Valor)')], help_text='Enfoque de la auditoría', max_length=20, verbose_name='Tipo de Auditoría')),
                ('estado', models.CharField(choices=[('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('con_diferencias', 'Completada con Diferencias')], default='en_proceso', max_length=20, verbose_name='Estado')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('observaciones_generales', models.TextField(blank=True, help_text='Comentarios sobre la auditoría', verbose_name='Observaciones Generales')),
                ('total_productos_auditados', models.IntegerField(default=0, verbose_name='Total Productos Auditados')),
                ('total_diferencias_encontradas', models.IntegerField(default=0, verbose_name='Total Diferencias Encontradas')),
                ('auditor', models.ForeignKey(help_text='Empleado que realiza la auditoría', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_almacen_realizadas', to='inventario.empleado', verbose_name='Auditor')),
                ('sucursal', models.ForeignKey(help_text='Sucursal donde se realiza la auditoría', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_almacen', to='inventario.sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': 'Auditorías',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ProductoAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(help_text='Código único del producto (SKU, código de barras, etc.)', max_length=50, unique=True, verbose_name='Código/SKU')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del producto', max_length=200, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada, especificaciones técnicas, etc.', verbose_name='Descripción')),
                ('tipo_producto', models.CharField(choices=[('resurtible', 'Resurtible (Stock Permanente)'), ('unico', 'Único (Compra Específica)')], default='resurtible', help_text='Resurtible: stock permanente. Único: compra específica.', max_length=20, verbose_name='Tipo de Producto')),
                ('ubicacion_fisica', models.CharField(blank=True, help_text='Ubicación en el almacén: pasillo-estante-nivel (ej: A-03-2)', max_length=50, verbose_name='Ubicación Física')),
                ('stock_actual', models.IntegerField(default=0, help_text='Cantidad disponible actualmente', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Actual')),
                ('stock_minimo', models.IntegerField(default=0, help_text='Nivel mínimo antes de alerta de reposición (solo resurtibles)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Mínimo')),
                ('stock_maximo', models.IntegerField(default=0, help_text='Nivel máximo recomendado (solo resurtibles)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Máximo')),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, help_text='Último costo de compra por unidad (MXN)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Unitario')),
                ('tiempo_reposicion_dias', models.IntegerField(default=7, help_text='Tiempo estimado para reponer stock', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tiempo de Reposición (días)')),
                ('imagen', models.ImageField(blank=True, help_text='Foto del producto para identificación visual', null=True, upload_to='almacen/productos/', verbose_name='Imagen del Producto')),
                ('qr_code', models.ImageField(blank=True, help_text='Código QR generado automáticamente', null=True, upload_to='almacen/qr_codes/', verbose_name='Código QR')),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar para ocultar sin eliminar', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('categoria', models.ForeignKey(blank=True, help_text='Categoría a la que pertenece el producto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='almacen.categoriaalmacen', verbose_name='Categoría')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_almacen_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('sucursal', models.ForeignKey(blank=True, help_text='Sucursal donde está el producto. Dejar vacío = almacén central.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_almacen', to='inventario.sucursal', verbose_name='Sucursal')),
                ('proveedor_principal', models.ForeignKey(blank=True, help_text='Proveedor habitual de este producto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_principales', to='almacen.proveedor', verbose_name='Proveedor Principal')),
            ],
            options={
                'verbose_name': 'Producto de Almacén',
                'verbose_name_plural': 'Productos de Almacén',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DiferenciaAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_sistema', models.IntegerField(help_text='Cantidad que indicaba el sistema', verbose_name='Stock en Sistema')),
                ('stock_fisico', models.IntegerField(help_text='Cantidad contada físicamente', verbose_name='Stock Físico')),
                ('diferencia', models.IntegerField(help_text='Stock físico - Stock sistema. Negativo = faltante.', verbose_name='Diferencia')),
                ('razon', models.CharField(choices=[('merma_natural', 'Merma Natural'), ('dano', 'Producto Dañado'), ('robo', 'Robo/Pérdida'), ('error_sistema', 'Error de Sistema'), ('error_recepcion', 'Error al Recibir'), ('error_despacho', 'Error al Despachar'), ('desconocida', 'Razón Desconocida')], help_text='Causa probable de la diferencia', max_length=20, verbose_name='Razón de Diferencia')),
                ('razon_detalle', models.TextField(blank=True, help_text='Explicación más detallada', verbose_name='Detalle de la Razón')),
                ('evidencia', models.ImageField(blank=True, help_text='Foto de la situación encontrada', null=True, upload_to='almacen/auditorias/evidencias/', verbose_name='Evidencia Fotográfica')),
                ('ajuste_realizado', models.BooleanField(default=False, help_text='¿Se ajustó el sistema al valor físico?', verbose_name='Ajuste Realizado')),
                ('fecha_ajuste', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Ajuste')),
                ('acciones_correctivas', models.TextField(blank=True, help_text='Qué se hizo para corregir o prevenir', verbose_name='Acciones Correctivas')),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diferencias', to='almacen.auditoria', verbose_name='Auditoría')),
                ('responsable_ajuste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes_auditoria_realizados', to='inventario.empleado', verbose_name='Responsable del Ajuste')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diferencias_auditoria', to='almacen.productoalmacen', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Diferencia de Auditoría',
                'verbose_name_plural': 'Diferencias de Auditoría',
                'ordering': ['-auditoria__fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='CompraProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(help_text='Número de unidades compradas', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('costo_unitario', models.DecimalField(decimal_places=2, help_text='Precio por unidad en esta compra (MXN)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Unitario')),
                ('costo_total', models.DecimalField(decimal_places=2, help_text='Cantidad × Costo Unitario (calculado automáticamente)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Total')),
                ('fecha_pedido', models.DateField(help_text='Fecha en que se realizó el pedido', verbose_name='Fecha de Pedido')),
                ('fecha_recepcion', models.DateField(blank=True, help_text='Fecha en que se recibió el producto', null=True, verbose_name='Fecha de Recepción')),
                ('dias_entrega', models.IntegerField(blank=True, help_text='Días entre pedido y recepción (calculado automáticamente)', null=True, verbose_name='Días de Entrega')),
                ('numero_factura', models.CharField(blank=True, help_text='Número de factura del proveedor', max_length=50, verbose_name='Número de Factura')),
                ('numero_orden_compra', models.CharField(blank=True, help_text='Número de orden de compra interno', max_length=50, verbose_name='Número de Orden de Compra')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre esta compra', verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('orden_servicio', models.ForeignKey(blank=True, help_text='Si esta compra es para un servicio técnico específico', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_piezas', to='servicio_tecnico.ordenservicio', verbose_name='Orden de Servicio')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('producto', models.ForeignKey(help_text='Producto que se compró', on_delete=django.db.models.deletion.CASCADE, related_name='historial_compras', to='almacen.productoalmacen', verbose_name='Producto')),
                ('proveedor', models.ForeignKey(help_text='Proveedor de esta compra específica', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_realizadas', to='almacen.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Compra de Producto',
                'verbose_name_plural': 'Compras de Productos',
                'ordering': ['-fecha_recepcion', '-fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudBaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_solicitud', models.CharField(choices=[('consumo_interno', 'Consumo Interno'), ('servicio_tecnico', 'Servicio Técnico'), ('venta_mostrador', 'Venta Mostrador'), ('transferencia', 'Transferencia entre Sucursales')], default='consumo_interno', help_text='Propósito de la salida del producto', max_length=20, verbose_name='Tipo de Solicitud')),
                ('cantidad', models.IntegerField(help_text='Número de unidades que se necesitan', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad Solicitada')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('observaciones', models.TextField(blank=True, help_text='Motivo o detalles de la solicitud', verbose_name='Observaciones del Solicitante')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('en_espera', 'En Espera - Producto no Disponible')], default='pendiente', help_text='Estado actual de la solicitud', max_length=20, verbose_name='Estado')),
                ('fecha_procesado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Procesamiento')),
                ('observaciones_agente', models.TextField(blank=True, help_text='Motivo de rechazo o notas del agente', verbose_name='Observaciones del Agente')),
                ('requiere_reposicion', models.BooleanField(default=False, help_text='Marcar si después de esta baja el producto quedará bajo mínimo', verbose_name='Requiere Reposición')),
                ('agente_almacen', models.ForeignKey(blank=True, help_text='Agente que aprobó o rechazó la solicitud', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_procesadas', to='inventario.empleado', verbose_name='Procesado por')),
                ('orden_servicio', models.ForeignKey(blank=True, help_text='Vincular con orden de servicio técnico (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_piezas_almacen', to='servicio_tecnico.ordenservicio', verbose_name='Orden de Servicio')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_baja', to='almacen.productoalmacen', verbose_name='Producto')),
                ('solicitante', models.ForeignKey(help_text='Empleado que solicita el producto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_almacen', to='inventario.empleado', verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitud de Baja',
                'verbose_name_plural': 'Solicitudes de Baja',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], help_text='Entrada: suma al stock. Salida: resta del stock.', max_length=10, verbose_name='Tipo de Movimiento')),
                ('cantidad', models.IntegerField(help_text='Número de unidades que entran o salen', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('costo_unitario', models.DecimalField(decimal_places=2, help_text='Costo por unidad al momento del movimiento', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Unitario')),
                ('stock_anterior', models.IntegerField(help_text='Stock antes del movimiento', verbose_name='Stock Anterior')),
                ('stock_posterior', models.IntegerField(help_text='Stock después del movimiento', verbose_name='Stock Posterior')),
                ('observaciones', models.TextField(blank=True, help_text='Notas sobre este movimiento', verbose_name='Observaciones')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('compra', models.ForeignKey(blank=True, help_text='Si este movimiento viene de una compra registrada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='almacen.compraproducto', verbose_name='Compra Asociada')),
                ('empleado', models.ForeignKey(help_text='Empleado que realizó o registró el movimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_almacen', to='inventario.empleado', verbose_name='Registrado por')),
                ('orden_servicio', models.ForeignKey(blank=True, help_text='Si este movimiento es para un servicio técnico', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piezas_almacen', to='servicio_tecnico.ordenservicio', verbose_name='Orden de Servicio')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='almacen.productoalmacen', verbose_name='Producto')),
                ('solicitud_baja', models.ForeignKey(blank=True, help_text='Solicitud que originó este movimiento (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='almacen.solicitudbaja', verbose_name='Solicitud de Baja')),
            ],
            options={
                'verbose_name': 'Movimiento de Almacén',
                'verbose_name_plural': 'Movimientos de Almacén',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='productoalmacen',
            index=models.Index(fields=['codigo_producto'], name='almacen_pro_codigo__ec3415_idx'),
        ),
        migrations.AddIndex(
            model_name='productoalmacen',
            index=models.Index(fields=['tipo_producto'], name='almacen_pro_tipo_pr_deb097_idx'),
        ),
        migrations.AddIndex(
            model_name='productoalmacen',
            index=models.Index(fields=['activo'], name='almacen_pro_activo_de3598_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudbaja',
            index=models.Index(fields=['estado'], name='almacen_sol_estado_f0f1f4_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudbaja',
            index=models.Index(fields=['fecha_solicitud'], name='almacen_sol_fecha_s_3269a0_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoalmacen',
            index=models.Index(fields=['tipo'], name='almacen_mov_tipo_d1a598_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoalmacen',
            index=models.Index(fields=['fecha'], name='almacen_mov_fecha_94f1f5_idx'),
        ),
    ]
