# Generated by Django 5.2.8 on 2025-12-03 04:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
        ('servicio_tecnico', '0018_alter_cotizacion_motivo_rechazo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(blank=True, help_text='Código único interno para esta unidad específica (autogenerado)', max_length=50, verbose_name='Código Interno')),
                ('numero_serie', models.CharField(blank=True, help_text='S/N del fabricante (si aplica)', max_length=100, verbose_name='Número de Serie')),
                ('marca', models.CharField(blank=True, help_text='Marca del fabricante (ej: Samsung, Kingston, Crucial)', max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, help_text='Modelo específico (ej: 870 EVO, A400, MX500)', max_length=100, verbose_name='Modelo')),
                ('especificaciones', models.TextField(blank=True, help_text='Detalles técnicos adicionales de esta unidad', verbose_name='Especificaciones')),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('usado_bueno', 'Usado - Buen Estado'), ('usado_regular', 'Usado - Estado Regular'), ('reparado', 'Reparado'), ('defectuoso', 'Defectuoso'), ('para_revision', 'Para Revisión')], default='nuevo', help_text='Condición física/funcional de la unidad', max_length=20, verbose_name='Estado')),
                ('disponibilidad', models.CharField(choices=[('disponible', 'Disponible'), ('reservada', 'Reservada'), ('asignada', 'Asignada a Orden'), ('vendida', 'Vendida'), ('descartada', 'Descartada/Baja')], default='disponible', help_text='Estado operativo actual', max_length=20, verbose_name='Disponibilidad')),
                ('origen', models.CharField(choices=[('compra', 'Compra Directa'), ('orden_servicio', 'Recuperada de Orden de Servicio'), ('devolucion_cliente', 'Devolución de Cliente'), ('transferencia', 'Transferencia entre Sucursales'), ('inventario_inicial', 'Inventario Inicial'), ('donacion', 'Donación'), ('otro', 'Otro')], default='compra', help_text='De dónde proviene esta unidad', max_length=30, verbose_name='Origen')),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, help_text='Costo pagado por esta unidad específica', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo de Adquisición')),
                ('ubicacion_especifica', models.CharField(blank=True, help_text='Ubicación exacta dentro del almacén (ej: Caja A-3)', max_length=50, verbose_name='Ubicación Específica')),
                ('notas', models.TextField(blank=True, help_text='Observaciones adicionales sobre esta unidad', verbose_name='Notas')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('compra', models.ForeignKey(blank=True, help_text='Registro de compra de donde proviene', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades', to='almacen.compraproducto', verbose_name='Compra')),
                ('orden_servicio_destino', models.ForeignKey(blank=True, help_text='OS a la que se asignó esta pieza (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_asignadas', to='servicio_tecnico.ordenservicio', verbose_name='Orden de Destino')),
                ('orden_servicio_origen', models.ForeignKey(blank=True, help_text='OS de donde se recuperó esta pieza (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_recuperadas', to='servicio_tecnico.ordenservicio', verbose_name='Orden de Origen')),
                ('producto', models.ForeignKey(help_text='Tipo de producto al que pertenece esta unidad', on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='almacen.productoalmacen', verbose_name='Producto')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Unidad de Inventario',
                'verbose_name_plural': 'Unidades de Inventario',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['producto', 'disponibilidad'], name='almacen_uni_product_8d29fd_idx'), models.Index(fields=['marca'], name='almacen_uni_marca_8ee426_idx'), models.Index(fields=['estado'], name='almacen_uni_estado_eb4442_idx'), models.Index(fields=['numero_serie'], name='almacen_uni_numero__f5ccec_idx'), models.Index(fields=['codigo_interno'], name='almacen_uni_codigo__f6dd8d_idx')],
            },
        ),
    ]
