# Generated by Django 5.2.8 on 2025-12-03 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_unidadinventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudbaja',
            name='unidad_inventario',
            field=models.ForeignKey(blank=True, help_text='Seleccionar si desea dar de baja una unidad específica (con marca/modelo/serie)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_baja', to='almacen.unidadinventario', verbose_name='Unidad Específica'),
        ),
    ]
