# Generated by Django 5.2.5 on 2025-12-03 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0003_add_unidad_inventario_to_solicitud_baja'),
        ('inventario', '0013_empleado_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudbaja',
            name='tecnico_asignado',
            field=models.ForeignKey(blank=True, help_text='Técnico de laboratorio que utilizará el producto (obligatorio para Servicio Técnico)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_tecnico_asignado', to='inventario.empleado', verbose_name='Técnico Asignado'),
        ),
    ]
