# Generated by Django 5.2.8 on 2025-12-04 06:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0004_add_tecnico_asignado_to_solicitud'),
        ('servicio_tecnico', '0019_alter_detalleequipo_tipo_equipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_linea', models.PositiveIntegerField(default=1, help_text='Número secuencial dentro de la compra (1, 2, 3...)', verbose_name='Número de Línea')),
                ('numero_serie', models.CharField(blank=True, help_text='S/N del fabricante (si se conoce al comprar)', max_length=100, verbose_name='Número de Serie')),
                ('marca', models.CharField(blank=True, choices=[('', '-- Seleccionar marca --'), ('Samsung', 'Samsung'), ('Kingston', 'Kingston'), ('Crucial', 'Crucial'), ('Western Digital', 'Western Digital'), ('Seagate', 'Seagate'), ('SanDisk', 'SanDisk'), ('SK Hynix', 'SK Hynix'), ('Toshiba', 'Toshiba'), ('Corsair', 'Corsair'), ('G.Skill', 'G.Skill'), ('ADATA', 'ADATA'), ('TeamGroup', 'TeamGroup'), ('Asus', 'Asus'), ('MSI', 'MSI'), ('Gigabyte', 'Gigabyte'), ('ASRock', 'ASRock'), ('Intel', 'Intel'), ('AMD', 'AMD'), ('Nvidia', 'Nvidia'), ('Dell', 'Dell'), ('HP', 'HP'), ('Lenovo', 'Lenovo'), ('Acer', 'Acer'), ('Apple', 'Apple'), ('Genérico', 'Genérico / Sin Marca'), ('Otra', 'Otra Marca')], help_text='Marca del fabricante (ej: Samsung, Kingston)', max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, help_text='Modelo específico (ej: 870 EVO, A400)', max_length=100, verbose_name='Modelo')),
                ('especificaciones', models.TextField(blank=True, help_text='Detalles técnicos adicionales de esta unidad', verbose_name='Especificaciones')),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, help_text='Costo específico de esta unidad (si difiere del general)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Unitario')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Recibir'), ('recibida', 'Recibida OK'), ('wpb', 'WPB - Pieza Incorrecta'), ('doa', 'DOA - Dañada al Llegar'), ('devolucion', 'En Devolución'), ('devuelta', 'Devuelta')], default='pendiente', help_text='Estado de recepción de esta unidad específica', max_length=20, verbose_name='Estado')),
                ('motivo_problema', models.TextField(blank=True, help_text='Descripción del problema si es WPB/DOA', verbose_name='Motivo del Problema')),
                ('fecha_recepcion', models.DateTimeField(blank=True, help_text='Cuándo se recibió esta unidad específica', null=True, verbose_name='Fecha de Recepción')),
                ('fecha_problema', models.DateTimeField(blank=True, help_text='Cuándo se detectó el problema', null=True, verbose_name='Fecha de Problema')),
                ('notas', models.TextField(blank=True, help_text='Observaciones adicionales', verbose_name='Notas')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Unidad de Compra',
                'verbose_name_plural': 'Unidades de Compra',
                'ordering': ['compra', 'numero_linea'],
            },
        ),
        migrations.AlterModelOptions(
            name='compraproducto',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Compra de Producto', 'verbose_name_plural': 'Compras de Productos'},
        ),
        migrations.AddField(
            model_name='compraproducto',
            name='estado',
            field=models.CharField(choices=[('pendiente_aprobacion', 'Pendiente de Aprobación'), ('aprobada', 'Aprobada por Cliente'), ('rechazada', 'Rechazada por Cliente'), ('pendiente_llegada', 'Pendiente de Llegada'), ('recibida', 'Recibida'), ('wpb', 'WPB - Wrong Part (Pieza Incorrecta)'), ('doa', 'DOA - Dead On Arrival (Dañada al Llegar)'), ('devolucion_garantia', 'En Devolución (Garantía)'), ('devuelta', 'Devuelta al Proveedor'), ('cancelada', 'Cancelada')], default='pendiente_aprobacion', help_text='Estado actual de la compra/cotización', max_length=25, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='compraproducto',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AddField(
            model_name='compraproducto',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, help_text='Cuándo el cliente aprobó la cotización', null=True, verbose_name='Fecha de Aprobación'),
        ),
        migrations.AddField(
            model_name='compraproducto',
            name='fecha_devolucion',
            field=models.DateTimeField(blank=True, help_text='Cuándo se confirmó la devolución al proveedor', null=True, verbose_name='Fecha de Devolución'),
        ),
        migrations.AddField(
            model_name='compraproducto',
            name='fecha_problema',
            field=models.DateTimeField(blank=True, help_text='Cuándo se detectó WPB/DOA', null=True, verbose_name='Fecha de Problema'),
        ),
        migrations.AddField(
            model_name='compraproducto',
            name='fecha_rechazo',
            field=models.DateTimeField(blank=True, help_text='Cuándo el cliente rechazó la cotización', null=True, verbose_name='Fecha de Rechazo'),
        ),
        migrations.AddField(
            model_name='compraproducto',
            name='motivo_problema',
            field=models.TextField(blank=True, help_text='Descripción del problema (WPB/DOA)', verbose_name='Motivo del Problema'),
        ),
        migrations.AddField(
            model_name='compraproducto',
            name='motivo_rechazo',
            field=models.TextField(blank=True, help_text='Razón por la cual el cliente rechazó la cotización', verbose_name='Motivo del Rechazo'),
        ),
        migrations.AddField(
            model_name='compraproducto',
            name='orden_cliente',
            field=models.CharField(blank=True, help_text='Número de orden visible para el cliente (ej: OS-2024-0001)', max_length=50, verbose_name='Número de Orden Cliente'),
        ),
        migrations.AddField(
            model_name='compraproducto',
            name='tipo',
            field=models.CharField(choices=[('cotizacion', 'Cotización'), ('compra', 'Compra Formal')], default='cotizacion', help_text='Cotización (pendiente aprobación) o Compra formal', max_length=15, verbose_name='Tipo de Registro'),
        ),
        migrations.AddIndex(
            model_name='compraproducto',
            index=models.Index(fields=['estado'], name='almacen_com_estado_b350c7_idx'),
        ),
        migrations.AddIndex(
            model_name='compraproducto',
            index=models.Index(fields=['tipo'], name='almacen_com_tipo_a83bd5_idx'),
        ),
        migrations.AddIndex(
            model_name='compraproducto',
            index=models.Index(fields=['orden_cliente'], name='almacen_com_orden_c_a1c26c_idx'),
        ),
        migrations.AddField(
            model_name='unidadcompra',
            name='compra',
            field=models.ForeignKey(help_text='Compra a la que pertenece esta unidad', on_delete=django.db.models.deletion.CASCADE, related_name='unidades_compra', to='almacen.compraproducto', verbose_name='Compra'),
        ),
        migrations.AddField(
            model_name='unidadcompra',
            name='unidad_inventario',
            field=models.OneToOneField(blank=True, help_text='UnidadInventario creada al recibir esta pieza', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidad_compra_origen', to='almacen.unidadinventario', verbose_name='Unidad de Inventario'),
        ),
        migrations.AlterUniqueTogether(
            name='unidadcompra',
            unique_together={('compra', 'numero_linea')},
        ),
    ]
