# Generated by Django 5.2.5 on 2025-12-04 22:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0005_unidadcompra_alter_compraproducto_options_and_more'),
        ('servicio_tecnico', '0020_solicitud_cotizacion_multiproveedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_solicitud', models.CharField(editable=False, help_text='Identificador único auto-generado (SOL-2025-0001)', max_length=20, unique=True, verbose_name='Número de Solicitud')),
                ('numero_orden_cliente', models.CharField(blank=True, db_index=True, help_text='Número visible para el cliente (ej: OOW-12345, FL-67890)', max_length=50, verbose_name='Número de Orden Cliente')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada_cliente', 'Enviada a Cliente'), ('parcialmente_aprobada', 'Parcialmente Aprobada'), ('totalmente_aprobada', 'Totalmente Aprobada'), ('totalmente_rechazada', 'Totalmente Rechazada'), ('en_proceso', 'En Proceso de Compra'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='borrador', help_text='Estado actual de la solicitud de cotización', max_length=25, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_envio_cliente', models.DateTimeField(blank=True, help_text='Cuándo se liberó para compartir con el cliente', null=True, verbose_name='Fecha Envío a Cliente')),
                ('fecha_respuesta_cliente', models.DateTimeField(blank=True, help_text='Cuándo el cliente respondió (última respuesta)', null=True, verbose_name='Fecha Respuesta Cliente')),
                ('fecha_completada', models.DateTimeField(blank=True, help_text='Cuándo se generaron todas las compras', null=True, verbose_name='Fecha Completada')),
                ('observaciones', models.TextField(blank=True, help_text='Notas internas sobre esta solicitud', verbose_name='Observaciones')),
                ('observaciones_cliente', models.TextField(blank=True, help_text='Comentarios o feedback del cliente', verbose_name='Observaciones del Cliente')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_cotizacion_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('orden_servicio', models.ForeignKey(blank=True, help_text='Orden de servicio técnico asociada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_cotizacion', to='servicio_tecnico.ordenservicio', verbose_name='Orden de Servicio')),
            ],
            options={
                'verbose_name': 'Solicitud de Cotización',
                'verbose_name_plural': 'Solicitudes de Cotización',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='LineaCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_linea', models.PositiveIntegerField(default=1, help_text='Orden de la línea dentro de la solicitud', verbose_name='Número de Línea')),
                ('descripcion_pieza', models.CharField(help_text='Descripción específica (ej: "RAM DDR4 16GB 3200MHz Kingston Fury")', max_length=255, verbose_name='Descripción de la Pieza')),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Número de unidades a cotizar', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('costo_unitario', models.DecimalField(decimal_places=2, help_text='Precio por unidad (MXN)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Unitario')),
                ('estado_cliente', models.CharField(choices=[('pendiente', 'Pendiente de Respuesta'), ('aprobada', 'Aprobada por Cliente'), ('rechazada', 'Rechazada por Cliente'), ('compra_generada', 'Compra Generada')], default='pendiente', help_text='Respuesta del cliente para esta línea', max_length=20, verbose_name='Estado del Cliente')),
                ('fecha_respuesta', models.DateTimeField(blank=True, help_text='Cuándo el cliente respondió', null=True, verbose_name='Fecha de Respuesta')),
                ('motivo_rechazo', models.TextField(blank=True, help_text='Si el cliente rechazó, por qué', verbose_name='Motivo de Rechazo')),
                ('notas', models.TextField(blank=True, help_text='Observaciones sobre esta línea', verbose_name='Notas')),
                ('tiempo_entrega_estimado', models.PositiveIntegerField(blank=True, help_text='Días estimados para recibir del proveedor', null=True, verbose_name='Tiempo de Entrega (días)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('compra_generada', models.OneToOneField(blank=True, help_text='CompraProducto creada al aprobar esta línea', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linea_cotizacion_origen', to='almacen.compraproducto', verbose_name='Compra Generada')),
                ('producto', models.ForeignKey(help_text='Producto del catálogo de almacén', on_delete=django.db.models.deletion.PROTECT, related_name='lineas_cotizacion', to='almacen.productoalmacen', verbose_name='Producto')),
                ('proveedor', models.ForeignKey(help_text='Proveedor donde se comprará esta pieza', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas_cotizacion', to='almacen.proveedor', verbose_name='Proveedor')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='almacen.solicitudcotizacion', verbose_name='Solicitud de Cotización')),
            ],
            options={
                'verbose_name': 'Línea de Cotización',
                'verbose_name_plural': 'Líneas de Cotización',
                'ordering': ['solicitud', 'numero_linea'],
            },
        ),
        migrations.AddIndex(
            model_name='solicitudcotizacion',
            index=models.Index(fields=['numero_solicitud'], name='almacen_sol_numero__df2373_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudcotizacion',
            index=models.Index(fields=['numero_orden_cliente'], name='almacen_sol_numero__bb2fe0_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudcotizacion',
            index=models.Index(fields=['estado'], name='almacen_sol_estado_45d477_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lineacotizacion',
            unique_together={('solicitud', 'numero_linea')},
        ),
    ]
