# Generated by Django 5.2.5 on 2025-12-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0006_solicitud_cotizacion_multiproveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='folio_referencia',
            field=models.CharField(blank=True, help_text='Identificador temporal (ej: número de serie) cuando no hay orden activa', max_length=100, verbose_name='Folio de Referencia'),
        ),
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='sin_orden_activa',
            field=models.BooleanField(default=False, help_text='Marcar si aún no existe una orden de servicio para esta cotización', verbose_name='Sin Orden Activa'),
        ),
        migrations.AlterField(
            model_name='lineacotizacion',
            name='numero_linea',
            field=models.PositiveIntegerField(default=0, help_text='Orden de la línea dentro de la solicitud (se asigna automáticamente)', verbose_name='Número de Línea'),
        ),
    ]
