# Generated by Django 5.2.5 on 2025-12-05 22:46

import almacen.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0007_add_sin_orden_activa_to_solicitud_cotizacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenLineaCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Imagen de referencia de la pieza (JPG, PNG, GIF, WebP). Máx 10MB.', upload_to=almacen.models.imagen_linea_cotizacion_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp'])], verbose_name='Imagen')),
                ('descripcion', models.CharField(blank=True, help_text='Descripción breve de la imagen (ej: "Etiqueta con modelo", "Vista frontal")', max_length=200, verbose_name='Descripción')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se subió la imagen', verbose_name='Fecha de Subida')),
                ('fue_comprimida', models.BooleanField(default=False, help_text='Indica si la imagen fue comprimida automáticamente', verbose_name='¿Fue Comprimida?')),
                ('tamano_original_kb', models.PositiveIntegerField(blank=True, help_text='Tamaño original del archivo antes de compresión', null=True, verbose_name='Tamaño Original (KB)')),
                ('tamano_final_kb', models.PositiveIntegerField(blank=True, help_text='Tamaño final del archivo después de procesamiento', null=True, verbose_name='Tamaño Final (KB)')),
                ('linea', models.ForeignKey(help_text='Línea de cotización a la que pertenece esta imagen', on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='almacen.lineacotizacion', verbose_name='Línea de Cotización')),
                ('subido_por', models.ForeignKey(help_text='Usuario que subió la imagen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagenes_cotizacion_subidas', to=settings.AUTH_USER_MODEL, verbose_name='Subido Por')),
            ],
            options={
                'verbose_name': 'Imagen de Línea de Cotización',
                'verbose_name_plural': 'Imágenes de Líneas de Cotización',
                'ordering': ['linea', 'fecha_subida'],
            },
        ),
    ]
