# Generated by Django 5.2.5 on 2026-01-15 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0008_add_imagen_linea_cotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudbaja',
            name='unidades_seleccionadas',
            field=models.ManyToManyField(blank=True, help_text='Unidades específicas seleccionadas para esta solicitud (obligatorio para trazabilidad)', related_name='solicitudes_baja_multiples', to='almacen.unidadinventario', verbose_name='Unidades Seleccionadas'),
        ),
    ]
