# Generated by Django 5.2.5 on 2026-01-16 05:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0009_solicitudbaja_unidades_seleccionadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadcompra',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, help_text='Cuántas piezas son de esta marca/modelo (ej: 5 Kingston, 3 Samsung)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad'),
        ),
    ]
