# Generated by Django 5.2.5 on 2026-01-20 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0010_add_cantidad_to_unidadcompra'),
        ('inventario', '0013_empleado_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudbaja',
            name='sucursal_destino',
            field=models.ForeignKey(blank=True, help_text='Solo para transferencias: sucursal a donde se enviará el producto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_entrantes', to='inventario.sucursal', verbose_name='Sucursal Destino'),
        ),
        migrations.AddField(
            model_name='unidadinventario',
            name='sucursal_actual',
            field=models.ForeignKey(blank=True, help_text='Sucursal donde está esta unidad. Vacío = Almacén Central', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_almacenadas', to='inventario.sucursal', verbose_name='Sucursal Actual'),
        ),
        migrations.AlterField(
            model_name='unidadinventario',
            name='ubicacion_especifica',
            field=models.CharField(blank=True, help_text='Ubicación exacta dentro del almacén (ej: Caja A-3, Estante 5)', max_length=50, verbose_name='Ubicación Específica'),
        ),
    ]
