# Generated by Django 5.2.5 on 2026-01-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0011_solicitudbaja_sucursal_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoalmacen',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('transferencia', 'Transferencia')], help_text='Entrada: suma al stock. Salida: resta del stock. Transferencia: no afecta stock.', max_length=15, verbose_name='Tipo de Movimiento'),
        ),
    ]
