# Generated by Django 5.2.5 on 2026-02-10 06:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0012_alter_movimientoalmacen_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compraproducto',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, help_text='Precio por unidad en esta compra', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Unitario'),
        ),
        migrations.AlterField(
            model_name='lineacotizacion',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, help_text='Precio por unidad', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Unitario'),
        ),
        migrations.AlterField(
            model_name='productoalmacen',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Último costo de compra por unidad', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Unitario'),
        ),
    ]
