# Generated by Django 5.2.5 on 2026-02-11 19:36

import almacen.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0013_alter_compraproducto_costo_unitario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diferenciaauditoria',
            name='evidencia',
            field=models.ImageField(blank=True, help_text='Foto de la situación encontrada', max_length=255, null=True, upload_to='almacen/auditorias/evidencias/', verbose_name='Evidencia Fotográfica'),
        ),
        migrations.AlterField(
            model_name='imagenlineacotizacion',
            name='imagen',
            field=models.ImageField(help_text='Imagen de referencia de la pieza (JPG, PNG, GIF, WebP). Máx 10MB.', max_length=255, upload_to=almacen.models.imagen_linea_cotizacion_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp'])], verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='productoalmacen',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Foto del producto para identificación visual', max_length=255, null=True, upload_to='almacen/productos/', verbose_name='Imagen del Producto'),
        ),
        migrations.AlterField(
            model_name='productoalmacen',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='Código QR generado automáticamente', max_length=255, null=True, upload_to='almacen/qr_codes/', verbose_name='Código QR'),
        ),
    ]
