# Generated by Django 5.2.5 on 2026-05-21 04:23

import config.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0014_alter_diferenciaauditoria_evidencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diferenciaauditoria',
            name='evidencia',
            field=models.ImageField(blank=True, help_text='Foto de la situación encontrada (JPG, PNG, GIF, WebP). Máx 10 MB.', max_length=255, null=True, upload_to='almacen/auditorias/evidencias/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp']), config.validators.FileSizeValidator(10)], verbose_name='Evidencia Fotográfica'),
        ),
        migrations.AlterField(
            model_name='productoalmacen',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Foto del producto para identificación visual (JPG, PNG, GIF, WebP). Máx 10 MB.', max_length=255, null=True, upload_to='almacen/productos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp']), config.validators.FileSizeValidator(10)], verbose_name='Imagen del Producto'),
        ),
    ]
