# Generated by Django 5.2.5 on 2026-06-10 04:34

import almacen.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0015_alter_diferenciaauditoria_evidencia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudcotizacion',
            name='folio_referencia',
        ),
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='email_cliente',
            field=models.EmailField(blank=True, help_text='Correo electrónico del cliente para enviar la cotización', max_length=254, verbose_name='Correo del Cliente'),
        ),
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='marca',
            field=models.CharField(blank=True, choices=[('', '-- Seleccione una marca --'), ('Acer', 'Acer'), ('Apple', 'Apple'), ('Asus', 'Asus'), ('Compaq', 'Compaq'), ('Dell', 'Dell'), ('Gateway', 'Gateway'), ('Gigabyte', 'Gigabyte'), ('HP', 'HP'), ('Huawei', 'Huawei'), ('Lenovo', 'Lenovo'), ('MSI', 'MSI'), ('Samsung', 'Samsung'), ('Sony', 'Sony'), ('Toshiba', 'Toshiba'), ('Otra', 'Otra Marca')], help_text='Marca del equipo del cliente', max_length=50, verbose_name='Marca del Equipo'),
        ),
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='modelo',
            field=models.CharField(blank=True, help_text='Modelo del equipo del cliente (texto libre)', max_length=100, verbose_name='Modelo del Equipo'),
        ),
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='nombre_cliente',
            field=models.CharField(blank=True, help_text='Nombre completo del cliente que solicita la cotización', max_length=200, verbose_name='Nombre del Cliente'),
        ),
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='service_tag',
            field=models.CharField(blank=True, help_text='Número de serie o identificador del equipo cuando no hay orden activa', max_length=100, verbose_name='Service Tag'),
        ),
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='telefono_cliente',
            field=models.CharField(blank=True, help_text='Número de contacto del cliente', max_length=20, verbose_name='Teléfono del Cliente'),
        ),
        migrations.AlterField(
            model_name='lineacotizacion',
            name='costo_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Precio por unidad (opcional, puede dejarse en 0 si aún no se conoce)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Unitario'),
        ),
        migrations.CreateModel(
            name='ImagenSolicitudCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Imagen de referencia (JPG, PNG, GIF, WebP). Máx 10MB.', max_length=255, upload_to=almacen.models.imagen_solicitud_cotizacion_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp'])], verbose_name='Imagen')),
                ('descripcion', models.CharField(blank=True, help_text='Descripción breve de la imagen', max_length=200, verbose_name='Descripción')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('fue_comprimida', models.BooleanField(default=False, verbose_name='¿Fue Comprimida?')),
                ('tamano_original_kb', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamaño Original (KB)')),
                ('tamano_final_kb', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamaño Final (KB)')),
                ('solicitud', models.ForeignKey(help_text='Solicitud a la que pertenece esta imagen de referencia', on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_referencia', to='almacen.solicitudcotizacion', verbose_name='Solicitud de Cotización')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagenes_solicitud_cotizacion_subidas', to=settings.AUTH_USER_MODEL, verbose_name='Subido Por')),
            ],
            options={
                'verbose_name': 'Imagen de Referencia de Solicitud',
                'verbose_name_plural': 'Imágenes de Referencia de Solicitud',
                'ordering': ['solicitud', 'fecha_subida'],
            },
        ),
    ]
