# Generated by Django 5.2.5 on 2026-06-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0016_remove_solicitudcotizacion_folio_referencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcotizacion',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('enviada_front', 'Enviada a Front'), ('enviada_cliente', 'Enviada a Cliente'), ('parcialmente_aprobada', 'Parcialmente Aprobada'), ('totalmente_aprobada', 'Totalmente Aprobada'), ('totalmente_rechazada', 'Totalmente Rechazada'), ('en_proceso', 'En Proceso de Compra'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='borrador', help_text='Estado actual de la solicitud de cotización', max_length=25, verbose_name='Estado'),
        ),
    ]
