# Generated by Django 5.2.5 on 2026-06-17 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0018_migrar_enviada_cliente_a_enviada_front'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='rfc_cliente',
            field=models.CharField(blank=True, help_text='RFC del cliente (opcional, 13 caracteres persona física, 12 persona moral)', max_length=13, verbose_name='RFC del Cliente'),
        ),
    ]
