# Generated by Django 5.2.5 on 2026-06-17 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0019_solicitudcotizacion_rfc_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='tipo_equipo',
            field=models.CharField(blank=True, choices=[('', '-- Seleccione un tipo de equipo --'), ('PC', 'PC'), ('Laptop', 'Laptop'), ('AIO', 'AIO (All-in-One)')], help_text='Tipo de equipo del cliente (PC, Laptop, AIO)', max_length=10, verbose_name='Tipo de Equipo'),
        ),
    ]
