# Generated by Django 5.2.5 on 2026-06-17 05:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0020_solicitudcotizacion_tipo_equipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaServicioAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_linea', models.PositiveIntegerField(default=0, help_text='Orden de la línea dentro de la solicitud (se asigna automáticamente)', verbose_name='Número de Línea')),
                ('tipo_servicio', models.CharField(choices=[('paquete_premium', 'Solución Premium'), ('paquete_oro', 'Solución Oro'), ('paquete_plata', 'Solución Plata'), ('cambio_pieza', 'Cambio de Pieza (sin diagnóstico)'), ('limpieza', 'Limpieza y Mantenimiento'), ('kit_limpieza', 'Kit de Limpieza Profesional'), ('reinstalacion_so', 'Reinstalación de Sistema Operativo'), ('respaldo', 'Respaldo de Información')], help_text='Tipo de servicio adicional (paquete, limpieza, reinstalación, etc.)', max_length=25, verbose_name='Tipo de Servicio')),
                ('costo', models.DecimalField(decimal_places=2, help_text='Precio del servicio (IVA incluido)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo del Servicio')),
                ('estado_cliente', models.CharField(choices=[('pendiente', 'Pendiente de Respuesta'), ('aprobada', 'Aprobada por Cliente'), ('rechazada', 'Rechazada por Cliente'), ('compra_generada', 'Compra Generada')], default='pendiente', help_text='Respuesta del cliente para este servicio', max_length=20, verbose_name='Estado del Cliente')),
                ('fecha_respuesta', models.DateTimeField(blank=True, help_text='Cuándo el cliente respondió', null=True, verbose_name='Fecha de Respuesta')),
                ('motivo_rechazo', models.TextField(blank=True, help_text='Si el cliente rechazó, por qué', verbose_name='Motivo de Rechazo')),
                ('notas', models.TextField(blank=True, help_text='Observaciones sobre este servicio', verbose_name='Notas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_adicionales', to='almacen.solicitudcotizacion', verbose_name='Solicitud de Cotización')),
            ],
            options={
                'verbose_name': 'Servicio Adicional',
                'verbose_name_plural': 'Servicios Adicionales',
                'ordering': ['solicitud', 'numero_linea'],
                'unique_together': {('solicitud', 'numero_linea')},
            },
        ),
    ]
