# Generated by Django 5.2.5 on 2026-06-17 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0021_lineaservicioadicional'),
        ('servicio_tecnico', '0041_detalleequipo_nombre_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineacotizacion',
            name='pieza_cotizada_origen',
            field=models.OneToOneField(blank=True, help_text='PiezaCotizada de servicio técnico que originó esta línea (sincronización automática)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linea_cotizacion_almacen', to='servicio_tecnico.piezacotizada', verbose_name='Pieza Cotizada Origen'),
        ),
    ]
