# Generated by Django 5.2.5 on 2026-06-23 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0022_lineacotizacion_pieza_cotizada_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineacotizacion',
            name='es_necesaria',
            field=models.BooleanField(default=True, help_text='¿Es necesaria para el funcionamiento? Desmarcar si es mejora estética o de rendimiento', verbose_name='¿Es necesaria?'),
        ),
        migrations.AddField(
            model_name='lineacotizacion',
            name='sugerida_por_tecnico',
            field=models.BooleanField(default=False, help_text='¿Fue sugerida por el técnico en su diagnóstico? (normalmente False para líneas de Almacén)', verbose_name='¿Sugerida por técnico?'),
        ),
    ]
