# Generated by Django 5.2.5 on 2026-07-16 17:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0028_lineacotizacion_opcion_pago_reac'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcotizacion',
            name='tipo_servicio_cliente',
            field=models.CharField(blank=True, choices=[('mostrador', 'Mostrador'), ('estandar', 'Estándar'), ('express', 'Express'), ('alta_gama', 'Alta Gama'), ('server', 'Server'), ('rep_nivel_componente', 'Reparación a nivel componente')], default='', help_text='Perfil de servicio usado al enviar la cotización por correo/PDF', max_length=20, verbose_name='Perfil de profit enviado al cliente'),
        ),
        migrations.CreateModel(
            name='ConfiguracionProfitPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.CharField(choices=[('mostrador', 'Mostrador'), ('estandar', 'Estándar'), ('express', 'Express'), ('alta_gama', 'Alta Gama'), ('server', 'Server'), ('rep_nivel_componente', 'Reparación nivel componente')], help_text='Clave del perfil usada por el cotizador (una fila por perfil).', max_length=40, unique=True, verbose_name='Perfil de servicio')),
                ('profit_target', models.DecimalField(decimal_places=4, help_text='Margen como fracción (0.36 = 36%). Debe ser menor que 1.', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Profit target')),
                ('costos_fijos', models.CharField(help_text='Gastos internos separados por coma, sin IVA (ej. 25,160).', max_length=100, verbose_name='Costos fijos')),
                ('diagnostico', models.DecimalField(decimal_places=2, default=0, help_text='Cargo de evaluación técnica incluido en el precio al cliente.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Diagnóstico (MXN sin IVA)')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profit_perfiles_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Configuración profit (perfil)',
                'verbose_name_plural': 'Configuraciones profit (perfiles)',
                'ordering': ['perfil'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionReacondicionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurso_front_desk_mensual', models.DecimalField(decimal_places=2, default=10000, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Recurso front desk mensual (MXN)')),
                ('pct_front_desk', models.DecimalField(decimal_places=4, default=0.21, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='% Front desk')),
                ('mantenimiento_materiales', models.DecimalField(decimal_places=2, default=25, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Mantenimiento materiales (MXN)')),
                ('gastos_operacion_ingeniero', models.DecimalField(decimal_places=2, default=160, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Gastos operación ingeniero (MXN)')),
                ('pct_overhead', models.DecimalField(decimal_places=4, default=0.01, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='% Overhead')),
                ('pct_mkt', models.DecimalField(decimal_places=4, default=0.01, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='% Marketing')),
                ('pct_comision_venta', models.DecimalField(decimal_places=4, default=0.036, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='% Comisión venta')),
                ('pct_margen_ganancia', models.DecimalField(decimal_places=4, default=0.194, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='% Margen de ganancia')),
                ('pct_iva', models.DecimalField(decimal_places=4, default=0.16, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='% IVA')),
                ('pct_comision_cobro_base', models.DecimalField(decimal_places=4, default=0.035, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='% Comisión cobro base')),
                ('pct_comision_3m', models.DecimalField(decimal_places=4, default=0.0469, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='% Comisión financiamiento 3 meses')),
                ('pct_comision_6m', models.DecimalField(decimal_places=4, default=0.0769, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='% Comisión financiamiento 6 meses')),
                ('pct_comision_12m', models.DecimalField(decimal_places=4, default=0.1289, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='% Comisión financiamiento 12 meses')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reacondicionado_config_actualizada', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Configuración reacondicionado',
                'verbose_name_plural': 'Configuración reacondicionado',
            },
        ),
    ]
