# Generated by Django 5.2.14 on 2026-07-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0029_configuracion_parametros_cotizador'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='detalle_rechazo',
            field=models.TextField(blank=True, help_text='Detalle / plantilla del rechazo a nivel solicitud. Se puede precargar con los comentarios de piezas y servicios.', verbose_name='Detalle del rechazo (cabecera)'),
        ),
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='motivo_rechazo',
            field=models.CharField(blank=True, choices=[('costo_alto', 'Costo muy elevado'), ('muchas_piezas', 'Demasiadas piezas a cambiar'), ('tiempo_largo', 'Tiempo de reparación muy largo'), ('falta_justificacion', 'Falta de justificación en diagnóstico'), ('no_vale_pena', 'No vale la pena reparar'), ('no_hay_partes', 'No hay partes en el mercado'), ('solo_venta_mostrador', 'Solo está interesado en la propuesta de venta mostrador'), ('falta_de_respuesta', 'Se cierra cotización por vigencia y falta de respuesta del cliente'), ('no_apto', 'Equipo no apto para diagnóstico o reparación'), ('rechazo_sin_decision', 'Cliente desea evaluar las opciones sin tomar decisión inmediata'), ('no_especifica_motivo', 'Cliente no especifica motivo, únicamente rechaza la cotización'), ('no_autorizado_por_empresa', 'Cliente informa que su empresa no autoriza la reparación'), ('otro', 'Otro motivo')], help_text='Motivo de catálogo cuando la solicitud queda totalmente rechazada sin orden de Servicio Técnico vinculada', max_length=30, verbose_name='Motivo de rechazo (cabecera)'),
        ),
    ]
