# Generated by Django 5.2.14 on 2026-07-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0030_solicitudcotizacion_motivo_detalle_rechazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineacotizacion',
            name='precio_unitario_cliente',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio cotizado al cliente por unidad; se congela en la primera aprobación o rechazo de la solicitud', max_digits=10, null=True, verbose_name='Precio unitario al cliente (sin IVA)'),
        ),
        migrations.AlterField(
            model_name='lineacotizacion',
            name='subtotal_cliente_sin_iva',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='cantidad × precio_unitario_cliente, guardado al congelar precios (primera respuesta del cliente)', max_digits=12, null=True, verbose_name='Subtotal cliente sin IVA'),
        ),
        migrations.AlterField(
            model_name='solicitudcotizacion',
            name='fecha_precios_cliente',
            field=models.DateTimeField(blank=True, help_text='Cuándo se calcularon y guardaron los precios al cliente (primera aprobación o rechazo de línea/servicio)', null=True, verbose_name='Fecha precios cliente'),
        ),
    ]
