# Generated by Django 5.2.14 on 2026-08-10 16:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0031_helptext_precios_primera_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineacotizacion',
            name='profit_aplicado',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Margen efectivo usado al cotizar esta pieza (ej. 0.36 = 36%). Parte del perfil de servicio y puede personalizarse por pieza respetando el mínimo según costo unitario. Null en servicios adicionales y líneas de reacondicionado.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0.99)], verbose_name='Profit aplicado (fracción)'),
        ),
        migrations.AlterField(
            model_name='configuracionprofitperfil',
            name='diagnostico',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Referencia / auditoría. Ya NO se incluye ni se diluye en la cotización de reparación; el diagnóstico se cobra al ingresar el equipo.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Diagnóstico (MXN sin IVA)'),
        ),
        migrations.AlterField(
            model_name='solicitudcotizacion',
            name='incluir_descuento_diagnostico_cliente',
            field=models.BooleanField(default=True, help_text='Legacy: ya no se descuenta el diagnóstico en cotizaciones nuevas. Se conserva por historial; el código siempre guarda False al enviar.', verbose_name='Descontar diagnóstico (envío al cliente)'),
        ),
        migrations.AlterField(
            model_name='solicitudcotizacion',
            name='precio_total_menos_diagnostico_cliente',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Legacy: en cotizaciones nuevas queda vacío (None). Antes guardaba el total con IVA restando el diagnóstico ya pagado.', max_digits=12, null=True, verbose_name='Total cliente menos diagnóstico'),
        ),
    ]
