# Generated by Django 5.2.14 on 2026-08-10 20:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0032_lineacotizacion_profit_aplicado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionRangoProfitMinimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.CharField(choices=[('mostrador', 'Mostrador'), ('estandar', 'Estándar'), ('express', 'Express'), ('alta_gama', 'Alta Gama'), ('server', 'Server'), ('rep_nivel_componente', 'Reparación nivel componente')], help_text='Tipo de cotización al que aplican estos mínimos (una fila por perfil).', max_length=40, unique=True, verbose_name='Perfil de servicio')),
                ('min_0_499', models.DecimalField(decimal_places=4, help_text='Fracción (ej. 0.45 = 45%). Aplica al costo unitario < $500.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0.99)], verbose_name='Mínimo $0–$499')),
                ('min_500_999', models.DecimalField(decimal_places=4, help_text='Fracción. Aplica al costo unitario de $500 a $999.99.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0.99)], verbose_name='Mínimo $500–$999')),
                ('min_1000_1499', models.DecimalField(decimal_places=4, help_text='Fracción. Aplica al costo unitario de $1000 a $1499.99.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0.99)], verbose_name='Mínimo $1000–$1499')),
                ('min_1500_mas', models.DecimalField(decimal_places=4, help_text='Fracción. Aplica al costo unitario desde $1500 en adelante.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0.99)], verbose_name='Mínimo $1500+')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rangos_profit_minimo_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Configuración rangos profit mínimo',
                'verbose_name_plural': 'Configuraciones rangos profit mínimo',
                'ordering': ['perfil'],
            },
        ),
    ]
