# Generated by Django 5.2.14 on 2026-08-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0033_configuracion_rango_profit_minimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='aviso_pnc_cliente_enviado',
            field=models.BooleanField(default=False, help_text='True si se notificó al cliente que no hay piezas disponibles (PNC). No implica que se haya enviado una cotización con precios.', verbose_name='Aviso PNC enviado al cliente'),
        ),
    ]
