# Generated by Django 5.2.14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0034_solicitudcotizacion_aviso_pnc_cliente_enviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='plantilla_pnc_front_enviada',
            field=models.BooleanField(
                default=False,
                help_text=(
                    'True si el último «Notificar a Front» usó la plantilla '
                    'partes no disponibles (PNC). Si fue cotización lista, queda False.'
                ),
                verbose_name='Plantilla PNC enviada a Front',
            ),
        ),
    ]
