# Generated by Django 5.2.14 on 2026-08-18 20:13

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0035_solicitudcotizacion_plantilla_pnc_front_enviada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='aviso_vencimiento_enviado',
            field=models.BooleanField(default=False, help_text='Evita que la tarea diaria avise dos veces por la misma ronda', verbose_name='Aviso de Vencimiento Enviado'),
        ),
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='fecha_inicio_vigencia',
            field=models.DateTimeField(blank=True, help_text='Cuándo arrancó el reloj de los 5 días hábiles (al notificar a Front)', null=True, verbose_name='Inicio de Vigencia'),
        ),
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='fecha_vencimiento_vigencia',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Fecha límite calculada (inicio + 5 días hábiles)', null=True, verbose_name='Vence la Vigencia'),
        ),
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='ronda_cotizacion',
            field=models.PositiveSmallIntegerField(default=1, help_text='Número de veces que se ha cotizado (1 = primera cotización)', verbose_name='Ronda de Cotización'),
        ),
        migrations.CreateModel(
            name='RondaCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ronda', models.PositiveSmallIntegerField(help_text='1 = cotización original, 2 = primera recotización, etc.', verbose_name='Número de Ronda')),
                ('fecha_inicio_vigencia', models.DateTimeField(blank=True, help_text='Cuándo arrancaron los 5 días hábiles de esta ronda', null=True, verbose_name='Inicio de Vigencia')),
                ('fecha_vencimiento', models.DateTimeField(blank=True, help_text='Fecha límite que tuvo esta ronda', null=True, verbose_name='Fecha de Vencimiento')),
                ('fecha_cierre', models.DateTimeField(auto_now_add=True, help_text='Cuándo se archivó esta ronda (se creó el snapshot)', verbose_name='Fecha de Cierre')),
                ('motivo_cierre', models.CharField(choices=[('recotizacion', 'Cerrada por recotización (vigencia vencida)'), ('respuesta_cliente', 'Cerrada por respuesta del cliente'), ('cancelada', 'Cerrada por cancelación de la solicitud')], default='recotizacion', help_text='Por qué terminó esta ronda de cotización', max_length=25, verbose_name='Motivo de Cierre')),
                ('snapshot_lineas', models.JSONField(blank=True, default=list, help_text='Copia de las líneas con costo y precio al cliente de esta ronda', verbose_name='Snapshot de Piezas')),
                ('snapshot_servicios', models.JSONField(blank=True, default=list, help_text='Copia de los servicios adicionales de esta ronda', verbose_name='Snapshot de Servicios')),
                ('costo_total_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Suma de cantidad × costo_unitario de todas las piezas', max_digits=12, verbose_name='Costo Total (Proveedor)')),
                ('precio_cliente_total_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Suma de los precios congelados que vio el cliente', max_digits=12, verbose_name='Precio Total al Cliente (sin IVA)')),
                ('observaciones', models.TextField(blank=True, help_text='Nota opcional de por qué se recotizó', verbose_name='Observaciones')),
                ('creada_por', models.ForeignKey(blank=True, help_text='Usuario que solicitó la recotización', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rondas_cotizacion_cerradas', to=settings.AUTH_USER_MODEL, verbose_name='Cerrada por')),
                ('solicitud', models.ForeignKey(help_text='Cotización a la que pertenece esta ronda', on_delete=django.db.models.deletion.CASCADE, related_name='rondas', to='almacen.solicitudcotizacion', verbose_name='Solicitud de Cotización')),
            ],
            options={
                'verbose_name': 'Ronda de Cotización',
                'verbose_name_plural': 'Rondas de Cotización',
                'ordering': ['solicitud', 'numero_ronda'],
                'unique_together': {('solicitud', 'numero_ronda')},
            },
        ),
    ]
