# Generated by Django 5.2.14 on 2026-09-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0036_solicitudcotizacion_aviso_vencimiento_enviado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoalmacen',
            name='clave_sat',
            field=models.CharField(blank=True, default='', help_text='ClaveProdServ de 8 dígitos. Vacía = la factura PUE usa 01010101 hasta que se capture.', max_length=8, verbose_name='Clave SAT'),
        ),
    ]
