# Generated by Django 5.2.5 on 2025-10-01 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatarios', models.TextField(help_text='Lista de destinatarios (JSON con nombres y emails)')),
                ('asunto', models.CharField(help_text='Asunto del email enviado', max_length=255)),
                ('mensaje_adicional', models.TextField(blank=True, help_text='Mensaje adicional incluido en el email (opcional)')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se envió la notificación')),
                ('enviado_por', models.CharField(default='Sistema', help_text='Usuario que envió la notificación', max_length=100)),
                ('exitoso', models.BooleanField(default=True, help_text='Si el envío fue exitoso')),
                ('mensaje_error', models.TextField(blank=True, help_text='Mensaje de error si el envío falló')),
                ('incidencia', models.ForeignKey(help_text='Incidencia sobre la que se envió la notificación', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='scorecard.incidencia')),
            ],
            options={
                'verbose_name': 'Notificación de Incidencia',
                'verbose_name_plural': 'Notificaciones de Incidencias',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
