# Generated by Django 5.2.5 on 2025-10-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0002_notificacionincidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='numero_orden',
            field=models.CharField(blank=True, help_text='Número de orden interna del servicio', max_length=50),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='numero_serie',
            field=models.CharField(help_text='Número de serie del equipo (Service Tag)', max_length=100),
        ),
    ]
