# Generated by Django 5.2.5 on 2025-10-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0003_incidencia_numero_orden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='area_tecnico',
            field=models.CharField(blank=True, help_text='Área del técnico responsable (auto-completado)', max_length=100),
        ),
    ]
