# Generated by Django 5.2.5 on 2025-10-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0005_atribuibilidad_y_notificaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del servicio (ej: Ingreso del equipo al CIS)', max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del servicio')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en listados (menor primero)')),
                ('activo', models.BooleanField(default=True, help_text='Servicio activo para selección')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servicio Realizado',
                'verbose_name_plural': 'Servicios Realizados',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='servicio_realizado',
        ),
        migrations.AddField(
            model_name='incidencia',
            name='servicio_realizado_old',
            field=models.CharField(blank=True, help_text='[DEPRECADO] Campo antiguo de servicio', max_length=200, null=True),
        ),
    ]
