# Generated by Django 5.2.5 on 2025-10-04 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0006_rename_servicio_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='servicio_realizado',
            field=models.ForeignKey(blank=True, help_text='Servicio que se realizó al equipo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidencias', to='scorecard.serviciorealizado'),
        ),
    ]
