# Generated by Django 5.2.5 on 2025-10-04 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0007_add_servicio_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidencia',
            name='servicio_realizado_old',
        ),
    ]
