# Generated by Django 5.2.5 on 2025-11-06 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0008_remove_old_servicio_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='marca',
            field=models.CharField(choices=[('', '-- Seleccione una marca --'), ('acer', 'Acer'), ('alienware', 'Alienware'), ('apple', 'Apple'), ('asus', 'Asus'), ('compaq', 'Compaq'), ('dell', 'Dell'), ('gateway', 'Gateway'), ('hp', 'HP'), ('huawei', 'Huawei'), ('lenovo', 'Lenovo'), ('msi', 'MSI'), ('samsung', 'Samsung'), ('sony', 'Sony'), ('toshiba', 'Toshiba'), ('otra', 'Otra Marca')], help_text='Marca del equipo (selecciona de la lista)', max_length=50),
        ),
    ]
