# Generated by Django 5.2.8 on 2025-11-12 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0009_alter_incidencia_marca'),
        ('servicio_tecnico', '0013_detalleequipo_email_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='orden_servicio',
            field=models.ForeignKey(blank=True, help_text='Orden de servicio técnico que generó esta incidencia (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_generadas', to='servicio_tecnico.ordenservicio'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='marca',
            field=models.CharField(choices=[('', '-- Seleccione una marca --'), ('acer', 'Acer'), ('apple', 'Apple'), ('asus', 'Asus'), ('compaq', 'Compaq'), ('dell', 'Dell'), ('gateway', 'Gateway'), ('hp', 'HP'), ('huawei', 'Huawei'), ('lenovo', 'Lenovo'), ('msi', 'MSI'), ('samsung', 'Samsung'), ('sony', 'Sony'), ('toshiba', 'Toshiba'), ('otra', 'Otra Marca')], help_text='Marca del equipo (selecciona de la lista)', max_length=50),
        ),
    ]
