# Generated by Django 5.2.5 on 2025-11-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0010_incidencia_orden_servicio_alter_incidencia_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='marca',
            field=models.CharField(choices=[('', '-- Seleccione una marca --'), ('Acer', 'Acer'), ('Apple', 'Apple'), ('Asus', 'Asus'), ('Compaq', 'Compaq'), ('Dell', 'Dell'), ('Gateway', 'Gateway'), ('HP', 'HP'), ('Huawei', 'Huawei'), ('Lenovo', 'Lenovo'), ('MSI', 'MSI'), ('Samsung', 'Samsung'), ('Sony', 'Sony'), ('Toshiba', 'Toshiba'), ('Otra', 'Otra Marca')], help_text='Marca del equipo (selecciona de la lista)', max_length=50),
        ),
    ]
