# Generated by Django 5.2.5 on 2026-02-11 19:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0011_alter_incidencia_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenciaincidencia',
            name='imagen',
            field=models.ImageField(help_text='Imagen de evidencia (JPG, PNG, GIF)', max_length=255, upload_to='scorecard/evidencias/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='marca',
            field=models.CharField(choices=[('', '-- Seleccione una marca --'), ('Acer', 'Acer'), ('Apple', 'Apple'), ('Asus', 'Asus'), ('Compaq', 'Compaq'), ('Dell', 'Dell'), ('Gateway', 'Gateway'), ('Gigabyte', 'Gigabyte'), ('HP', 'HP'), ('Huawei', 'Huawei'), ('Lenovo', 'Lenovo'), ('MSI', 'MSI'), ('Samsung', 'Samsung'), ('Sony', 'Sony'), ('Toshiba', 'Toshiba'), ('Otra', 'Otra Marca')], help_text='Marca del equipo (selecciona de la lista)', max_length=50),
        ),
    ]
