# Generated by Django 5.2.5 on 2026-06-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0012_alter_evidenciaincidencia_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='numero_orden',
            field=models.CharField(blank=True, help_text='Número de orden del cliente (ej: OOW-12345). Si no hay orden de cliente, se usa el número de orden interno.', max_length=50),
        ),
    ]
